from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

def read(path: str) -> str:
    return (ROOT / path).read_text(encoding='utf-8')

version = read('app/version.php')
editor = read('app/remote_file/remote_editor.php')
api = read('public/remote_file_editor_api.php')
page = read('public/remote-editor.php')
js = read('public/js/remote-editor.js')

checks: list[bool] = []
def check(condition: bool, label: str) -> None:
    checks.append(bool(condition))
    print(('PASS' if condition else 'FAIL') + ': ' + label)

check("const APP_VERSION = '1.30.0-dev." in version, 'current V1.30 development version is visible')
check("const APP_VERSION_LABEL = 'RSS Reader Modernization 1.30.0-dev." in version, 'visible version label tracks V1.30 development checkpoint')
check("const APP_ASSET_REVISION = '1.30.0-dev." in version, 'asset revision tracks V1.30 development checkpoint')

check("preg_match('/\\A[0-9a-f]{64}\\z/D'" in editor, 'expected optimistic state is strict lowercase SHA-256')
check('remote_editor_validate_browser_text($text);' in editor, 'browser text is validated before save construction')
check("str_contains($text, \"\\r\")" in editor, 'direct API CR input is rejected to avoid ambiguous EOL state')
check("$lineEnding === 'crlf'" in editor and 'str_replace("\\n", "\\r\\n", $text)' in editor, 'CRLF source style is reconstructed on save')
check("$current['utf8_bom']" in editor and '"\\xEF\\xBB\\xBF" . $bytes' in editor, 'UTF-8 BOM is preserved on save')
check('remote_editor_inspect_bytes($pathInfo[\'path\'], $saveBytes)' in editor, 'final reconstructed bytes are revalidated against content and size rules')
check('$provider = remote_service_provider($ownerId, $connectionId);' in editor, 'save reuses shared owner-scoped provider construction')
check('remote_editor_read_with_provider($provider' in editor, 'save conflict checks use one protocol-neutral provider')
check('remote_service_assert_safe_path($provider, $pathInfo[\'path\'], false, false);' in editor, 'each provider read reuses existing path/symlink fail-closed check')
check('$provider->download($pathInfo[\'path\'], $stream, APP_REMOTE_EDITOR_MAX_BYTES);' in editor, 'save-side reads remain bounded by editor byte ceiling')
check("'.iguguru-editor-' . bin2hex(random_bytes(16)) . '.tmp'" in editor, 'staged remote sibling uses random non-user-controlled name')
check('remote_path_child($parent, $name)' in editor, 'staged path stays in the target parent directory')
check('$provider->upload($stream, $size, $stagePath, false);' in editor, 'stage upload refuses overwrite and supports size zero')
check(editor.count("throw new AppRemoteEditorException('editor_conflict', 409)") >= 2, 'save has pre-stage and post-stage optimistic conflict stops')
check(editor.count('hash_equals($expected') >= 2, 'SHA comparison uses constant-time hash_equals for both conflict checks')
check('$provider->move($stagePath, $pathInfo[\'path\'], true);' in editor, 'final provider move requests overwrite through common interface')
check("$prepared['sha256']" in editor and "$saved['sha256']" in editor, 'save verifies final remote bytes after replacement')
check("'editor_save_verification_failed', 502" in editor, 'read-back mismatch has explicit verification failure')
check('finally {' in editor and '$provider->delete($stagePath, false);' in editor, 'failed/conflicted staged file has best-effort cleanup')
check('Cleanup failure must not hide the original save/conflict error.' in editor, 'cleanup failure cannot mask original operation error')
check('not described as an atomic cross-protocol replacement' in editor, 'code explicitly avoids atomicity guarantee')
check('file locking' in editor, 'remaining no-lock race is documented')
check(all(proto not in editor.lower() for proto in ["'ftp'", "'ftps'", "'sftp'", "'webdav'"]), 'editor save has no protocol-specific branch')
check('error_log(' not in editor, 'editor backend does not log source content or path data')

check("in_array($method, ['GET', 'POST'], true)" in api, 'editor API is explicitly GET/POST only')
check('app_session_user_id()' in api, 'editor API requires authenticated user')
check("$contentType !== 'application/json'" in api and "explode(';', $contentTypeRaw, 2)" in api, 'save API requires exact application/json media type')
check('remote_editor_base64_max_bytes() + 65536' in api, 'save request envelope is derived from bounded Base64 transport')
check('stream_get_contents($stream, remote_editor_request_max_bytes() + 1)' in api, 'request body is bounded even without Content-Length')
check('app_csrf_is_valid($csrf)' in api, 'save API enforces CSRF')
check("'csrf_invalid'" in api, 'CSRF failure has stable error code')
check("$connectionId = app_validate_positive_int($input['remote_connection_id'] ?? null);" in api, 'save validates owner-scoped connection id input')
check("$path = remote_path_normalize_relative($input['path'] ?? null);" in api, 'save normalizes connection-relative path')
check("$encoded = $input['text_base64'] ?? null;" in api and "$expectedSha256 = $input['expected_sha256'] ?? null;" in api, 'save requires Base64 text plus expected SHA state')
check('base64_decode($encoded, true)' in api and 'base64_encode($decoded) !== $encoded' in api, 'save transport is strict canonical Base64')
check("$input['text']" not in api, 'raw source text field is not accepted by save API')
check("remote_editor_save($userId, $connectionId, $path, $text, $expectedSha256)" in api, 'decoded text dispatches only to dedicated editor save backend')
check("'editor_conflict' => 'The remote file changed after it was opened. Reload before saving.'" in api, '409 conflict has explicit public message')
check("remote_api_failure('editor.save', $userId, $exception)" in api, 'unexpected save failures use existing credential-safe mapper')
check('JSON_HEX_TAG' in api and 'JSON_HEX_AMP' in api and 'JSON_HEX_APOS' in api and 'JSON_HEX_QUOT' in api, 'editor API keeps defensive JSON HEX escaping')
check("Cross-Origin-Resource-Policy: same-origin" in api and "frame-ancestors 'none'" in api, 'editor API keeps same-origin and anti-framing headers')
check('app_send_no_store_headers()' in api, 'editor API remains no-store')

check('<meta name="csrf-token"' in page, 'editor page exposes only normal CSRF token meta for same-origin save')
check('V1.30-E checkpoint' in js, 'current E checkpoint guidance is rendered by editor JS')
check('競合時はSaveを停止' in js, 'current guidance tells user conflict blocks stale save')
check('id="remoteEditorSave" disabled aria-disabled="true"' in page, 'Save starts disabled until remote text is loaded and changed')
check('<span>保存</span>' in page, 'Save button has mutable visible label for saving state')

check("document.querySelector('meta[name=\"csrf-token\"]')" in js, 'editor JS reads CSRF from page meta')
check("method: 'POST'" in js and "Content-Type': 'application/json;charset=UTF-8'" in js, 'editor save uses dedicated JSON POST')
check("csrf_token: csrfToken()" in js, 'editor JSON save sends CSRF token')
check('expected_sha256: state.sha256' in js, 'editor JSON save sends optimistic SHA state')
check('text_base64: textBase64' in js and 'utf8ToBase64(el.text.value)' in js, 'editor sends current textarea as Base64 UTF-8 transport')
check('text: el.text.value' not in js, 'editor request omits raw source text field')
check("credentials: 'same-origin'" in js, 'editor save keeps same-origin credentials')
check('state.saving' in js and 'state.loading' in js, 'UI tracks loading/saving to prevent overlapping operations')
check('!state.dirty' in js, 'clean editor cannot trigger unnecessary save')
check("el.save.addEventListener('click', saveRemoteText);" in js, 'Save button is wired to dedicated save routine')
check("event.ctrlKey || event.metaKey" in js and 'saveRemoteText();' in js, 'Ctrl/Cmd+S uses same save path')
check("error.code === 'editor_conflict'" in js, 'client recognizes backend conflict code')
check('上書きせず停止しました' in js, 'conflict UX explicitly says overwrite was stopped')
check('state.conflicted' in js and '競合' in js, 'client tracks an explicit conflicted state')
check('state.conflicted || state.loading || state.saving' in js, 'conflicted state blocks stale Save')
check('state.sha256 = typeof data.sha256' in js, 'successful save updates optimistic state token')
check('state.initialText = el.text.value' in js and 'setDirty(false)' in js, 'successful save resets clean baseline')
check('syncCsrf(response)' in js, 'client accepts rotated CSRF token response header')
check('window.confirm' not in js.split('async function saveRemoteText()',1)[1].split('function confirmDiscard()',1)[0], 'normal save has no repetitive confirmation dialog')
check('innerHTML' not in js, 'source and errors are never injected through innerHTML')
check('localStorage' not in js and 'sessionStorage' not in js, 'source is not persisted in browser storage')
check('console.' not in js, 'source/editor state is not written to browser console')
check('force_overwrite' not in js.lower() and 'overwrite: true' not in js.lower(), 'client exposes no force-overwrite bypass')

failed = len(checks) - sum(checks)
print(f'RESULT: PASS {sum(checks)} / FAIL {failed} / SKIP 0')
raise SystemExit(1 if failed else 0)
