#!/usr/bin/env bash
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
SCRIPT_DIR="$ROOT/tests"
GROUP=${1:-}

case "$GROUP" in
  pre-calendar)
    python3 "$SCRIPT_DIR/test_v119c_registration_throttle.py"
    python3 "$SCRIPT_DIR/test_v119c_api_request_limit.py"
    python3 "$SCRIPT_DIR/test_current_drawer_contract.py"
    node --check "$ROOT/public/js/drawer-categories.js"
    python3 "$SCRIPT_DIR/test_v122b_feed_health.py"
    php "$SCRIPT_DIR/test_v122b_feed_health_runtime.php"
    node --check "$ROOT/public/js/feed-health.js"
    node --check "$ROOT/public/js/rss-management.js"
    python3 "$SCRIPT_DIR/test_v122c_rss_rules.py"
    php "$SCRIPT_DIR/test_v122c_rss_rules_runtime.php"
    python3 "$SCRIPT_DIR/test_v122d_rss_rules.py"
    php "$SCRIPT_DIR/test_v122d_rss_rule_engine_runtime.php"
    node --check "$ROOT/public/js/rss-rules.js"
    node --check "$ROOT/public/js/rss-rule-display.js"
    node --check "$ROOT/public/js/rss-rules-integration.js"
    python3 "$SCRIPT_DIR/test_v124b_memo_contract.py"
    node --check "$ROOT/public/js/memo-counter.js"
    php "$SCRIPT_DIR/test_v124c_stock_state.php"
    python3 "$SCRIPT_DIR/test_v124c_stock_state_static.py"
    php "$SCRIPT_DIR/test_v124d_stock_state_ui.php"
    php "$SCRIPT_DIR/test_v124e_stock_state_filters.php"
    node "$SCRIPT_DIR/test_v124e_stock_state_ui.js"
    python3 "$SCRIPT_DIR/test_v124e_stock_state_workflow_static.py"
    node --check "$ROOT/public/js/stock-state-ui.js"
    ;;
  calendar)
    php "$SCRIPT_DIR/test_v1_25_b_calendar_time_contract.php"
    php "$SCRIPT_DIR/test_v1_25_b_calendar_time_validation.php"
    php "$SCRIPT_DIR/test_v1_25_c_calendar_event_ui_contract.php"
    php "$SCRIPT_DIR/test_v1_25_d_recurrence_contract.php"
    php "$SCRIPT_DIR/test_v1_25_d_recurrence_validation.php"
    php "$SCRIPT_DIR/test_v1_25_e_calendar_source_actions_contract.php"
    php "$SCRIPT_DIR/test_v1_25_f_calendar_polish_contract.php"
    php "$SCRIPT_DIR/test_v1_25_f_calendar_polish_r3_contract.php"
    php "$SCRIPT_DIR/test_v1_33_c_calendar_range.php"
    python3 "$SCRIPT_DIR/test_v1_33_c_calendar_range_http.py"
    python3 "$SCRIPT_DIR/test_v1_33_c_calendar_range_contract.py"
    node "$SCRIPT_DIR/test_v1_33_c_calendar_range_ui.js"
    node "$SCRIPT_DIR/test_v1_33_c_calendar_submit_ui.js"
    php "$SCRIPT_DIR/test_v1_33_d_calendar_exception.php"
    python3 "$SCRIPT_DIR/test_v1_33_d_calendar_exception_http.py"
    python3 "$SCRIPT_DIR/test_v1_33_d_calendar_exception_contract.py"
    sh "$SCRIPT_DIR/test_v1_33_d_mariadb_migration.sh"
    python3 "$SCRIPT_DIR/test_v1_33_e_calendar_occurrence_contract.py"
    node "$SCRIPT_DIR/test_v1_33_e_calendar_occurrence_ui.js"
    python3 "$SCRIPT_DIR/test_v1_33_f_calendar_month_layout_contract.py"
    node "$SCRIPT_DIR/test_v1_33_f_calendar_month_layout.js"
    node "$SCRIPT_DIR/test_v1_33_f_calendar_month_dom.js"
    python3 "$SCRIPT_DIR/test_v1_33_g_calendar_views_contract.py"
    node "$SCRIPT_DIR/test_v1_33_g_calendar_views.js"
    node "$SCRIPT_DIR/test_v1_33_g_calendar_views_dom.js"
    python3 "$SCRIPT_DIR/test_v1_33_g_r1_calendar_toolbar_contract.py"
    python3 "$SCRIPT_DIR/test_v1_33_i_final_release.py"
    php -l "$ROOT/app/calendar_exception.php"
    node --check "$ROOT/public/js/calendar-core.js"
    node --check "$ROOT/public/js/calendar-occurrence.js"
    node --check "$ROOT/public/js/calendar-month-layout.js"
    node --check "$ROOT/public/js/calendar-views.js"
    node --check "$ROOT/public/js/calendar.js"
    node "$SCRIPT_DIR/test_v1_33_rc2_asset_loader.js"
    node --check "$ROOT/public/js/calendar-recurrence.js"
    node --check "$ROOT/public/js/calendar-event-details.js"
    node --check "$ROOT/public/js/calendar-source-actions.js"
    node --check "$ROOT/public/js/calendar-polish.js"
    node --check "$ROOT/public/js/calendar-polish-r3.js"
    ;;
  post-calendar)
    php "$SCRIPT_DIR/test_v1_26_b_info_board_backend.php"
    python3 "$SCRIPT_DIR/test_v1_26_b_info_board_static.py"
    python3 "$SCRIPT_DIR/test_v1_26_c_info_board_ui.py"
    node --check "$ROOT/public/js/info-board.js"
    python3 "$SCRIPT_DIR/test_v1_26_d_info_board_ticker.py"
    node "$SCRIPT_DIR/test_v1_26_d_info_board_ticker.js"
    node --check "$ROOT/public/js/info-board-ticker.js"
    php "$SCRIPT_DIR/url_normalizer_v127b_test.php"
    php "$SCRIPT_DIR/user_file_v127d_test.php"
    php "$SCRIPT_DIR/file_library_v127e_test.php"
    php "$SCRIPT_DIR/file_preview_current_v128g_test.php"
    php "$SCRIPT_DIR/file_library_current_v128g_test.php"
    node --check "$ROOT/public/js/file-library.js"
    node --check "$ROOT/public/js/file-library-core.js"
    node --check "$ROOT/public/js/file-library-text-preview.js"
    node --check "$ROOT/public/js/file-library-csv-preview.js"
    node --check "$ROOT/public/js/file-library-ui.js"
    php "$SCRIPT_DIR/remote_file_v129b_security_test.php"
    python3 "$SCRIPT_DIR/remote_file_v129b_static_test.py"
    php "$SCRIPT_DIR/remote_file_v129c_provider_test.php"
    python3 "$SCRIPT_DIR/remote_file_v129c_static_test.py"
    php -d auto_prepend_file="$ROOT/app/remote_file/remote_permission_provider.php" "$SCRIPT_DIR/remote_file_v129g_operations_test.php"
    php "$SCRIPT_DIR/remote_file_v129g_service_path_test.php"
    python3 "$SCRIPT_DIR/remote_file_v129h_integration_static.py"
    python3 "$SCRIPT_DIR/remote_file_v129i_ui_security_test.py"
    python3 "$SCRIPT_DIR/remote_file_v129i_credential_submit_r1_test.py"
    python3 "$SCRIPT_DIR/remote_file_v129i_env_check_r2_test.py"
    python3 "$SCRIPT_DIR/remote_file_v1331_multi_upload_static_test.py"
    node "$SCRIPT_DIR/remote_file_v1331_multi_upload_runtime_test.js"
    node --check "$ROOT/public/js/remote-files.js"
    python3 "$SCRIPT_DIR/test_current_remote_editor.py"
    php "$SCRIPT_DIR/remote_editor_v130b_text_test.php"
    php "$SCRIPT_DIR/remote_editor_v130d_save_test.php"
    python3 "$SCRIPT_DIR/remote_editor_v130d_api_http_test.py"
    node "$SCRIPT_DIR/remote_editor_v130d_ui_runtime_test.js"
    node "$SCRIPT_DIR/remote_editor_v130d_r3_navigation_runtime_test.js"
    php "$SCRIPT_DIR/remote_editor_v130e_roundtrip_test.php"
    node "$SCRIPT_DIR/remote_editor_v130e_ui_runtime_test.js"
    node --check "$ROOT/public/js/remote-editor.js"
    node --check "$ROOT/public/js/remote-files.js"
    php "$SCRIPT_DIR/test_current_remote_permissions.php"
    python3 "$SCRIPT_DIR/test_current_remote_permissions_static.py"
    node --check "$ROOT/public/js/remote-permissions.js"
    python3 "$SCRIPT_DIR/test_current_mail_contract.py"
    php -l "$ROOT/app/mail/mail_account.php"
    php -l "$ROOT/app/mail/mail_api.php"
    php -l "$ROOT/app/mail/mail_attachment.php"
    php -l "$ROOT/app/mail/mail_message.php"
    php -l "$ROOT/app/mail/mail_received_attachment.php"
    php -l "$ROOT/app/mail/mail_reply.php"
    php -l "$ROOT/app/mail/mail_sent.php"
    php -l "$ROOT/app/mail/mail_service.php"
    php -l "$ROOT/app/mail/mail_smtp_client.php"
    php -l "$ROOT/public/api_v1.php"
    node --check "$ROOT/public/js/mail-widget.js"
    php "$SCRIPT_DIR/test_current_totp.php"
    php "$SCRIPT_DIR/test_current_totp_window.php"
    php "$SCRIPT_DIR/test_current_recovery_code.php"
    php "$SCRIPT_DIR/test_current_recovery_code_api.php"
    php "$SCRIPT_DIR/test_current_step_up.php"
    php "$SCRIPT_DIR/test_current_account_security_api.php"
    php "$SCRIPT_DIR/test_current_session_registry.php"
    php "$SCRIPT_DIR/test_current_auth_audit.php"
    python3 "$SCRIPT_DIR/test_current_account_security_contract.py"
    python3 "$SCRIPT_DIR/test_current_step_up_contract.py"
    python3 "$SCRIPT_DIR/test_current_session_registry_contract.py"
    python3 "$SCRIPT_DIR/test_current_auth_audit_contract.py"
    python3 "$SCRIPT_DIR/test_current_account_security_release_gate.py"
    node --check "$ROOT/public/js/account-2fa.js"
    node --check "$ROOT/public/js/totp-qr.js"
    ;;
  *)
    echo "usage: $0 {pre-calendar|calendar|post-calendar}" >&2
    exit 2
    ;;
esac
