from pathlib import Path
import re, sys
ROOT=Path(__file__).resolve().parents[1]
widget=(ROOT/'app/dashboard_widget.php').read_text(encoding='utf-8')
api=(ROOT/'app/api.php').read_text(encoding='utf-8')
index=(ROOT/'public/index.php').read_text(encoding='utf-8')
js=(ROOT/'public/js/dashboard.js').read_text(encoding='utf-8')
css=(ROOT/'public/css/dashboard.css').read_text(encoding='utf-8')
conf=(ROOT/'app/common/common_conf.php').read_text(encoding='utf-8')
version=(ROOT/'app/version.php').read_text(encoding='utf-8')
run=(ROOT/'tests/run.sh').read_text(encoding='utf-8')
checks=[]
def check(cond,msg): checks.append(bool(cond)); print(('PASS' if cond else 'FAIL')+': '+msg)
check("'task'" in widget.split('function dashboard_widget_types',1)[1].split('}',1)[0], 'Task is an allowed Dashboard Widget type')
check("'task'" in conf and 'dashboard_widget' in conf, 'Task table is in the logical DB allowlist')
check('dashboard_widget_task_defaults' in widget and "'title' => 'Task'" in widget, 'Task Widget config has a small default')
check('dashboard_widget_validate_task_widget_title' in widget and ', 32, false' in widget, 'Task Widget title is bounded')
check('dashboard_widget_validate_task_title' in widget and ', 128, false' in widget, 'Task item title is bounded')
check('DateTimeImmutable::createFromFormat' in widget and "'!Y-m-d'" in widget, 'Task due date is parsed as an exact calendar date')
check("['low', 'normal', 'high']" in widget, 'Task priority uses an explicit allowlist')
check('dashboard_widget_validate_boolean' in widget and 'task_completed' in widget, 'Task completion is normalized as a boolean')
check("'task' => dashboard_widget_task_config_from_storage" in widget, 'Task rows receive normalized config')
check("FROM ' . db_table_identifier('task')" in widget, 'Task items are loaded from the dedicated table')
check('task_owner = :task_owner' in widget and 'task_widget_id IN (' in widget, 'Task loading is owner and Widget scoped')
check('task_flag = 0' in widget, 'logical deleted Tasks are excluded')
check('task_completed ASC, task_sort_order ASC' in widget, 'incomplete Tasks remain before completed Tasks')
check('dashboard_widget_normalize_task_row' in widget, 'Task DB rows pass one normalizer')
check('dashboard_widget_create_task_widget' in widget and 'dashboard_widget_update_task_widget' in widget and 'dashboard_widget_delete_task_widget' in widget, 'Task Widget CRUD is implemented in the domain layer')
check('dashboard_widget_create_task_item' in widget and 'dashboard_widget_update_task_item' in widget, 'Task item create and update are implemented')
check('dashboard_widget_toggle_task_item' in widget and 'dashboard_widget_delete_task_item' in widget, 'Task completion and logical delete are implemented')
check('dashboard_widget_lock_owned_widget' in widget and 'dashboard_widget_lock_owned_task' in widget and 'FOR UPDATE' in widget, 'Task mutations lock owner-scoped rows')
check(widget.count('beginTransaction()') >= 9 and widget.count('rollBack()') >= 9, 'Task writes preserve transactional rollback paths')
check('>= 100' in widget and 'up to 100 Tasks' in widget, 'Task count per Widget is bounded')
check("'widget.task.create' =>" in api and "'widget.task.update' =>" in api and "'widget.task.delete' =>" in api, 'Task Widget API actions are registered')
for action in ['task.item.create','task.item.update','task.item.toggle','task.item.delete']:
    check(f"'{action}' =>" in api, f'{action} API action is registered')
check('dashboard_widget_create_task_widget($userId' in api and 'dashboard_widget_create_task_item($userId' in api, 'Task ownership comes from authenticated user id')
check('task_owner' not in api[api.find('function api_widget_task_create'):api.find('function api_stock_create')], 'Task API never trusts a client owner field')
check("api_error('not_found'" in api and "api_error('task_unavailable'" in api, 'Task API has controlled not-found and DB failure responses')
check('data-dashboard-widget-type="task"' in index and 'task-card' in index, 'Task renders as a Dashboard Widget')
check('app_html($taskTitle)' in index and 'app_html($taskWidgetTitle)' in index, 'Task titles are escaped at output')
check('data-task-priority="' in index and 'data-task-due-date="' in index, 'Task edit data uses explicit bounded attributes')
check('aria-live="polite"' in index and 'task-toggle' in index, 'Task list has accessible live and completion controls')
check('id="registerTaskWidgetForm"' in index and 'id="changeTaskWidgetForm"' in index and 'id="changeTaskItemForm"' in index, 'Task forms are explicit')
check('maxlength="128"' in index and 'type="date"' in index, 'Task item inputs are bounded and use a date control')
check('Task追加' in index and 'fa-tasks' in index, 'Drawer exposes Task Widget addition')
for action in ['widget.task.create','widget.task.update','widget.task.delete','task.item.create','task.item.update','task.item.toggle','task.item.delete']:
    check(f"apiRequest('{action}'" in js, f'Frontend sends {action} through the central API helper')
check('.html(' not in js, 'Dashboard JS keeps text-only DOM operations')
check("window.confirm('このTask Widgetと中のTaskを削除しますか？')" in js, 'Task Widget deletion has explicit confirmation')
check("window.confirm('このTaskを削除しますか？')" in js, 'Task item deletion has explicit confirmation')
check(".off('submit' + eventNamespace, '.task-item-create-form')" in js, 'Task inline create handler is namespaced')
check('.task-card' in css and '.task-card-inner' in css and '.task-card-body' in css, 'Task participates in Dashboard card layout')
check('.task-completed .task-item-title' in css and 'text-decoration: line-through' in css, 'completed Tasks have a restrained visual state')
check('.task-create-options' in css and 'grid-template-columns' in css, 'Task inline form has a bounded responsive layout')
check('@media (max-width: 767.98px)' in css and '.task-card-body' in css, 'Task has a mobile layout rule')
check((re.search(r"const APP_VERSION = '1\.1\.0-dev\.[7-9][0-9]*';", version) is not None and any(label in version for label in ['V1.1-H / R1','V1.1-I / R1','V1.1-I / R2','V1.1-J / R1'])) or ("const APP_VERSION = '1.1.0';" in version and 'RSS Reader Modernization 1.1.0' in version), 'visible Version marker is V1.1-H or later')
check('test_v11h_task_widget.php' in run and 'test_v11h_frontend_runtime.js' in run, 'main regression runner includes V1.1-H checks')
if not all(checks):
    print(f'{sum(1 for x in checks if not x)}/{len(checks)} V1.1-H architecture checks failed')
    sys.exit(1)
print(f'All {len(checks)} V1.1-H architecture checks passed.')
