from pathlib import Path
import subprocess, sys
ROOT=Path(__file__).resolve().parents[1]
schema=(ROOT/'database/schema.sql').read_text(encoding='utf-8')
migration=(ROOT/'database/migrations/006_v1_1_calendar_event.sql').read_text(encoding='utf-8')
pre=(ROOT/'database/audit/v1_1_i_preflight.sql').read_text(encoding='utf-8')
post=(ROOT/'database/audit/v1_1_i_postflight.sql').read_text(encoding='utf-8')
tool=(ROOT/'tools/db_v11i.php').read_text(encoding='utf-8')
gitignore=(ROOT/'.gitignore').read_text(encoding='utf-8')
checks=[]
def check(cond,msg): checks.append(bool(cond)); print(('PASS' if cond else 'FAIL')+': '+msg)
check("SET @t_calendar_event = CONCAT('`', @table_prefix, 'calendar_event`');" in schema, 'new schema derives Calendar event table from configured prefix')
check("'CREATE TABLE ', @t_calendar_event" in schema, 'new installs create Calendar event table')
cols=['calendar_event_id','calendar_event_date','calendar_event_updated_at','calendar_event_flag','calendar_event_owner','calendar_event_title','calendar_event_start_date','calendar_event_end_date','calendar_event_note']
for col in cols:
    check(f'`{col}`' in schema and f'`{col}`' in migration, f'Calendar column {col} exists in schema and migration')
check('BIGINT UNSIGNED NOT NULL AUTO_INCREMENT' in migration, 'Calendar event id uses unsigned BIGINT')
check('calendar_event_start_date` DATE NOT NULL' in migration and 'calendar_event_end_date` DATE NOT NULL' in migration, 'Calendar event range uses DATE columns')
check('calendar_event_note` TEXT NOT NULL' in migration, 'Calendar note uses bounded application text over TEXT storage')
check('idx_calendar_event_owner_range' in migration, 'Calendar month lookup has owner/range index')
check('calendar_event_owner`, `calendar_event_flag`, `calendar_event_start_date`, `calendar_event_end_date`' in migration, 'Calendar index begins with owner and active range fields')
check('CREATE TABLE IF NOT EXISTS' in migration, 'existing DB migration is idempotent')
check("SET @table_prefix = 'ig_';" in migration, 'manual migration makes prefix selection explicit')
check('FOREIGN KEY' not in migration.upper(), 'Calendar migration adds no foreign key to Legacy data')
check(all(word not in pre.upper() for word in ['INSERT ','UPDATE ','DELETE ','DROP ','ALTER ','CREATE ']), 'preflight is read-only')
check(all(word not in post.upper() for word in ['INSERT ','UPDATE ','DELETE ','DROP ','ALTER ','CREATE ']), 'postflight is read-only')
check('information_schema.COLUMNS' in post and 'information_schema.STATISTICS' in post, 'postflight reports Calendar columns and indexes')
check('calendar_event_end_date < calendar_event_start_date' in post, 'postflight detects invalid stored ranges')
check('task_due_date IS NOT NULL' in post and "widget_type = ''calendar''" in post, 'postflight reports Task integration and Calendar Widgets')
check('apply --backup-confirmed' in tool and 'verify is read-only' in tool, 'CLI separates apply and read-only verify')
check("db_table_name('calendar_event')" in tool and "db_table_identifier('calendar_event')" in tool, 'CLI uses safe prefixed identifiers')
check('information_schema.TABLES' in tool and 'SHOW COLUMNS' in tool and 'SHOW INDEX' in tool, 'CLI verifies table, columns and indexes')
check("Apply V1.1-H first" in tool, 'Calendar migration refuses missing Task/Widget foundation')
check('Calendar event with end date before start date' in tool, 'CLI reports invalid active ranges')
check('!/database/migrations/006_v1_1_calendar_event.sql' in gitignore, 'Calendar migration is explicitly versionable')
check('!/database/audit/v1_1_i_preflight.sql' in gitignore and '!/database/audit/v1_1_i_postflight.sql' in gitignore, 'Calendar audit SQL is explicitly versionable')
proc=subprocess.run(['php',str(ROOT/'tools/db_v11i.php'),'--help'],cwd=ROOT,text=True,capture_output=True)
check(proc.returncode==0 and 'db_v11i.php verify' in proc.stdout, 'Calendar DB CLI help runs without DB access')
if not all(checks): sys.exit(1)
print(f'All {len(checks)} V1.1-I SQL checks passed.')
