'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..');let checks=0;
function check(value,name){assert.ok(value,name);checks++;console.log('PASS: '+name);}
function card(id,type){return `<section class="mini-game-card dashboard-widget" data-widget-width="1" data-widget-height="1" data-dashboard-widget-id="${id}" data-dashboard-widget-type="game" data-mini-game-type="${type}"><div class="mini-game-card-inner"><div class="mini-game-card-header"><button class="widget-drag-handle">並替</button><span class="mini-game-title">${type}</span></div><div class="mini-game-card-body">Loading</div></div></section>`;}
function html(source){const php=fs.readFileSync(path.join(root,'public',source),'utf8'),modals=source==='stock.php'?php:fs.readFileSync(path.join(root,'app/view/dashboard_modals.php'),'utf8');const menu=php.match(/<li class="drawer-section-title">[^\n]*<span>Widget追加<\/span><\/li>([\s\S]*?)(?=<li class="drawer-section-title">)/),select=modals.match(/<select\b[^>]*\bid="registerGameType"[^>]*>[\s\S]*?<\/select>/);assert.ok(menu&&select);return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/bootstrap-5.3.8.min.css"><link rel="stylesheet" href="/css/dashboard.css"><link rel="stylesheet" href="/css/mini-game.css"><link rel="stylesheet" href="/css/game-widget.css"></head><body><button id="outside">外側</button><button id="openDrawer" data-bs-toggle="offcanvas" data-bs-target="#drawerMenu">Menu</button><nav id="drawerMenu" class="offcanvas offcanvas-end"><ul class="drawer-menu">${menu[0]}</ul></nav><div id="registerGameWidget" class="modal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form id="registerGameWidgetForm">${select[0]}<input class="registerGameTitleValue" value="Icon Quest"></form></div></div></div><div id="main-content" data-dashboard-user-id="7"><div class="dashboard-grid">${card(1,'word_tiles')+card(2,'word_tiles')+card(3,'maze_chase')+card(4,'falling_blocks')}</div></div><div style="height:1200px"></div><script src="/js/jquery-3.7.1.min.js"></script><script src="/js/bootstrap.bundle-5.3.8.min.js"></script><script src="/js/game-widget.js?v=word-fixture"></script><script src="/js/mini-game.js"></script><script src="/js/lights-out.js"></script><script src="/js/cursor-field.js"></script><script src="/js/game-2048.js"></script><script src="/js/reversi.js"></script><script src="/js/block-collapse.js"></script><script src="/js/dashboard-core.js"></script><script src="/js/dashboard.js"></script><script src="/js/utility-widgets.js"></script></body></html>`;}
(async()=>{const browser=await chromium.launch({executablePath:process.env.GAME_TEST_CHROME||chromium.executablePath(),headless:true,args:['--no-sandbox']});
async function setup(width,source,options={}){const context=await browser.newContext({viewport:{width,height:1100},hasTouch:width<600}),requests=[],errors=[];let fail=options.fail?1:0;await context.addInitScript(({blocked,session})=>{window.__frames=0;const raf=requestAnimationFrame;window.requestAnimationFrame=fn=>raf(t=>{window.__frames++;fn(t);});if(blocked||session)Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}});if(blocked)Object.defineProperty(window,'sessionStorage',{get(){throw Error('blocked');}});},{blocked:!!options.blocked,session:!!options.session});await context.route('http://words.test/**',async route=>{const url=new URL(route.request().url());requests.push(url.pathname+url.search);if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:options.noWord?html(source).replace(card(1,'word_tiles')+card(2,'word_tiles'),''):html(source)});if(url.pathname===(options.dictionaryFail?'/js/word-tiles-words-en.js':'/js/word-tiles.js')&&fail-- >0)return route.abort();const file=path.join(root,'public',url.pathname);return fs.existsSync(file)?route.fulfill({body:fs.readFileSync(file),contentType:url.pathname.endsWith('.js')?'text/javascript':'text/css'}):route.fulfill({status:404,body:''});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://words.test/');return{page,context,requests,errors};}
for(const source of ['index.php','stock.php'])for(const width of [1280,360]){const e=await setup(width,source),p=e.page;await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===4);const first=p.locator('[data-dashboard-widget-id="1"]'),second=p.locator('[data-dashboard-widget-id="2"]');const rack=i=>first.locator('[data-word-rack="'+i+'"]'),cell=i=>first.locator('[data-word-cell="'+i+'"]'),action=x=>first.locator('[data-word-action="'+x+'"]');
check(e.requests.filter(x=>x.includes('word-tiles.js')).length===1,'multiple Word widgets share one module request: '+source+'/'+width);check(e.requests.includes('/js/word-tiles.js?v=word-fixture'),'Word module inherits revision');check(e.requests.filter(x=>x.includes('word-tiles-words-en.js')).length===1&&e.requests.includes('/js/word-tiles-words-en.js?v=word-fixture'),'dictionary loads once with revision');check(await first.locator('.word-tiles-cell').count()===81&&await first.locator('.word-tiles-tile').count()===7,'Word renders 81 cells and seven rack buttons');check(await first.getAttribute('data-game-widget-status')==='ready','new Word widget starts stopped');await first.locator('.word-tiles-dictionary summary').click();await first.locator('.word-tiles-search').fill('zebra');check((await first.locator('.word-tiles-search-results').textContent()).includes('ZEBRA：登録あり'),'new English word is searchable');await first.locator('.word-tiles-search').fill('CTA');check((await first.locator('.word-tiles-search-results').textContent()).includes('CTA：未登録'),'invalid word search');await first.locator('.word-tiles-search').fill('<img>');check(await first.locator('.word-tiles-dictionary img').count()===0,'dictionary search is XSS safe');await first.locator('.word-tiles-dictionary summary').click();
await p.locator('#openDrawer').click();await p.waitForSelector('#drawerMenu.show');await p.locator('[data-bs-target="#widgetCatalog-game"]').click();await p.locator('#widgetCatalog-game [data-game-preset="word_tiles"] .drawer-item-label').click();await p.waitForSelector('#registerGameWidget.show');check(await p.inputValue('#registerGameType')==='word_tiles'&&await p.inputValue('.registerGameTitleValue')==='Word Tiles','production Game menu opens Word add modal');await p.evaluate(()=>bootstrap.Modal.getInstance(document.getElementById('registerGameWidget')).hide());await p.waitForSelector('#registerGameWidget.show',{state:'hidden'});check(await p.locator('#widgetCatalog-game [data-game-preset="word_tiles"]').count()===1,'Word menu does not duplicate');
await first.locator('.game-widget-start').click();check(await first.getAttribute('data-game-widget-status')==='playing','Start activates Word board');
check(await cell(40).evaluate(c=>!c.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}))),'Word arrow navigation is scoped to board');check(await p.locator('#outside').evaluate(c=>c.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}))),'outside arrows retain page behavior');
async function put(index,ri){if(width===360){await rack(ri).tap();await cell(index).tap();}else{await rack(ri).click();await cell(index).click();}}
await put(39,0);await put(40,2);await put(41,1);await action('submit').click();check((await first.locator('.game-widget-status').textContent()).includes('CTA')&&await first.locator('.game-widget-score').textContent()==='0','unregistered word is rejected without scoring');check(await first.locator('.word-tiles-pending').count()===3,'rejected placement remains correctable');await action('clear').click();
await put(39,0);await put(40,1);await put(41,2);check(await first.locator('.word-tiles-pending').count()===3,'mouse/touch places CAT');await p.reload();await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===4);check(await first.locator('.word-tiles-pending').count()===3,'uncommitted placement restores after reload');await action('submit').click();check(await first.locator('.game-widget-score').textContent()==='3'&&await first.locator('.word-tiles-locked').count()===3,'CAT commits and scores three');check(await second.locator('.game-widget-score').textContent()==='0','one Word score does not affect the other');
await put(49,3);await put(58,4);await action('submit').click();check(await first.locator('.game-widget-score').textContent()==='6'&&(await first.locator('.game-widget-status').textContent()).includes('ARE'),'connected vertical word scores correctly');await p.reload();await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===4);check(await first.locator('.game-widget-score').textContent()==='6'&&await first.locator('.word-tiles-locked').count()===5,'board/rack/score restore after reload');
await first.locator('.game-widget-pause').click();check(await action('submit').isDisabled()&&await rack(0).isDisabled(),'Pause disables Word actions');await p.evaluate(()=>{jQuery(document).trigger('show.bs.modal');jQuery(document).trigger('hidden.bs.modal');});check(await first.locator('.game-widget-pause').textContent()==='Resume','Modal closure preserves manual Pause');await first.locator('.game-widget-pause').click();
await p.evaluate(()=>document.documentElement.setAttribute('data-bs-theme','dark'));await first.locator('.game-widget-expand').click();check(await first.locator('[aria-modal="true"]').count()===1,'Word expands with dark-theme dialog semantics');await first.locator('.game-widget-expand').press('Escape');check(await p.evaluate(()=>document.body.style.overflow)!=='hidden','Escape restores page scroll');
await action('exchange').click();check(await first.locator('.game-widget-score').textContent()==='6','rack exchange preserves score');check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'actual grid has no page overflow');check(await rack(0).evaluate(b=>b.getBoundingClientRect().height>=44),'rack touch targets are 44px');
await action('finish').click();check(await first.getAttribute('data-game-widget-status')==='gameover'&&await first.locator('.game-widget-pause').isDisabled(),'Finish ends solo game');await first.locator('.game-widget-start').click();check(await first.locator('.game-widget-score').textContent()==='0'&&await first.locator('.word-tiles-locked').count()===0&&await first.locator('.game-widget-best').textContent()==='6','Restart clears board and retains Best');
await p.evaluate(()=>{const c=document.querySelector('[data-dashboard-widget-id="1"]');c.setAttribute('data-mini-game-type','falling_blocks');jQuery(document).trigger('iguguru:widget-card-refreshed');});await first.locator('.falling-blocks-board').waitFor();check(await first.locator('.word-tiles-board').count()===0,'type change destroys Word UI');await p.evaluate(()=>{const c=document.querySelector('[data-dashboard-widget-id="1"]');c.setAttribute('data-mini-game-type','word_tiles');jQuery(document).trigger('iguguru:widget-card-refreshed');});await first.locator('.word-tiles-board').waitFor();check(await first.locator('.falling-blocks-board').count()===0,'switching back restores Word without stale engine');
await p.evaluate(()=>RssGameWidget.removeWidgetState(1));check(await p.evaluate(()=>localStorage.getItem(RssGameWidget.storageKey(7,1,'word_tiles')+'.state')===null&&localStorage.getItem(RssGameWidget.storageKey(7,2,'word_tiles')+'.state')!==null),'cleanup removes only the target Word saved state');
check(await p.locator('[data-dashboard-widget-id="3"] .maze-chase-board').count()===1&&await p.locator('[data-dashboard-widget-id="4"] .falling-blocks-board').count()===1,'Maze and Falling still mount alongside Word');check(e.errors.length===0,'no Word/browser exceptions: '+source+'/'+width);await e.context.close();}
const noWord=await setup(800,'index.php',{noWord:true});await noWord.page.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===2);check(noWord.requests.every(x=>!x.includes('word-tiles')),'dashboard without Word loads neither engine nor dictionary');check(noWord.errors.length===0,'non-Word dashboard has no exceptions');await noWord.context.close();
for(const options of [{blocked:true},{session:true},{fail:true},{fail:true,dictionaryFail:true}]){const e=await setup(800,'index.php',options),p=e.page;if(options.fail){await p.locator('[data-dashboard-widget-id="1"]').getByRole('button',{name:'再試行',exact:true}).click();await p.locator('[data-dashboard-widget-id="2"]').getByRole('button',{name:'再試行',exact:true}).click();}await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===4);if(options.blocked)check((await p.locator('.word-tiles-save-note').first().textContent()).includes('画面内'),'blocked Storage uses memory');if(options.session)check((await p.locator('.word-tiles-save-note').first().textContent()).includes('Tab'),'localStorage failure falls back to sessionStorage');if(options.fail)check(e.requests.filter(x=>x.includes(options.dictionaryFail?'word-tiles-words-en.js':'word-tiles.js')).length===2,'failed Word lazy load can retry');check(e.errors.length===0,'storage/retry produces no exceptions');await e.context.close();}
const e=await setup(800,'index.php'),p=e.page;await p.waitForSelector('.word-tiles-board');await p.evaluate(()=>localStorage.setItem(RssGameWidget.storageKey(7,1,'word_tiles')+'.state','{"schema":1,"board":["<img src=x onerror=alert(1)>"]}'));await p.reload();await p.waitForSelector('.word-tiles-board');check(await p.locator('.word-tiles-cell img').count()===0&&await p.locator('[data-dashboard-widget-id="1"]').getAttribute('data-game-widget-status')==='ready','corrupt/script-like stored state resets safely');await e.context.close();await browser.close();console.log('RESULT: PASS '+checks+' / FAIL 0 / SKIP 0');})().catch(error=>{console.error(error);process.exit(1);});
