'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..'),rows=[{widget_id:1,widget_owner:7,widget_location:0,widget_type:'calendar',widget_reference_id:null,widget_flag:0,widget_sort_order:0,widget_style:'primary',widget_width:1,widget_height:1,widget_config:JSON.stringify({schema:1,title:'Calendar',show_completed_tasks:false})}];
const markup=execFileSync('php',[path.join(__dirname,'fixtures/widget_header_page.php'),JSON.stringify(rows)],{encoding:'utf8'});
const styles=['bootstrap-5.3.8.min','dashboard','calendar-colors','calendar-event-details','calendar-recurrence','calendar-month-layout','calendar-views','calendar-polish','calendar-polish-r3','calendar-deadline'];
const scripts=['jquery-3.7.1.min','bootstrap.bundle-5.3.8.min','calendar-month-layout','calendar-views','calendar-core','calendar-occurrence','calendar-recurrence','calendar-event-details','calendar-copy','calendar-deadline'];
const html='<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="csrf-token" content="'+'a'.repeat(64)+'">'+styles.map(s=>'<link rel="stylesheet" href="/css/'+s+'.css">').join('')+'</head><body>'+markup+scripts.map(s=>'<script src="/js/'+s+'.js"></script>').join('')+'</body></html>';
const base={kind:'event',note:'',color:'blue',all_day:true,start_time:null,end_time:null,url:null,reminder:'none',repeat_type:'none',repeat_until:null,source_start_date:'2026-10-10',source_end_date:'2026-10-10',original_occurrence_start_date:'2026-10-10'};
const events=[
 {...base,event_id:1,title:'明日期限',deadline_highlight:true,occurrence_key:'event:1:2026-10-10',occurrence_start_date:'2026-10-10',occurrence_end_date:'2026-10-10'},
 {...base,event_id:2,title:'2日前',deadline_highlight:true,occurrence_key:'event:2:2026-10-11',occurrence_start_date:'2026-10-11',occurrence_end_date:'2026-10-11',source_start_date:'2026-10-11',source_end_date:'2026-10-11',original_occurrence_start_date:'2026-10-11'},
 {...base,event_id:3,title:'強調なし',deadline_highlight:false,occurrence_key:'event:3:2026-10-10',occurrence_start_date:'2026-10-10',occurrence_end_date:'2026-10-10'}
];
let checks=0;function check(ok,name){assert(ok,name);checks++;console.log('PASS: '+name);}
(async()=>{const browser=await chromium.launch({executablePath:process.env.GAME_TEST_CHROME||chromium.executablePath(),headless:true,args:['--no-sandbox']});try{for(const width of [1280,360]){
 const context=await browser.newContext({viewport:{width,height:1000},timezoneId:'Asia/Tokyo'});let requests=0;const errors=[];
 await context.addInitScript(()=>{const D=Date;window.__now=D.parse('2026-10-09T12:00:00+09:00');window.Date=class extends D{constructor(...args){super(...(args.length?args:[window.__now]));}static now(){return window.__now;}};window.__hidden=false;Object.defineProperty(document,'hidden',{get:()=>window.__hidden});window.__pulseStarts=0;const add=DOMTokenList.prototype.add;DOMTokenList.prototype.add=function(...tokens){if(tokens.includes('calendar-deadline-pulse'))window.__pulseStarts++;return add.apply(this,tokens);};const timeout=setTimeout.bind(window),clear=clearTimeout.bind(window),deadlineTimers=new Set();window.setTimeout=(fn,ms,...args)=>{const own=String(new Error().stack||'').includes('calendar-deadline.js');let id;id=timeout(()=>{deadlineTimers.delete(id);fn(...args);},ms);if(own)deadlineTimers.add(id);return id;};window.clearTimeout=id=>{deadlineTimers.delete(id);clear(id);};window.__deadlineTimerCount=()=>deadlineTimers.size;window.__advance=ms=>{window.__now+=ms;};window.__setHidden=value=>{window.__hidden=!!value;document.dispatchEvent(new Event('visibilitychange'));};});
 await context.route('http://cal.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:html});if(u.pathname.endsWith('.php')){requests++;const p=new URLSearchParams(route.request().postData()||'');return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,data:{events,tasks:[],holidays:{},cancelled_occurrences:[],range_start:p.get('calendar_range_start')||'2026-10-01',range_end:p.get('calendar_range_end')||'2026-10-31'}})});}const file=path.join(root,'public',u.pathname);return fs.existsSync(file)?route.fulfill({body:fs.readFileSync(file),contentType:u.pathname.endsWith('.js')?'text/javascript':'text/css'}):route.fulfill({status:404,body:''});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const sync=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.goto('http://cal.test/');await page.waitForSelector('[data-calendar-range-ready="1"]');await page.waitForFunction(()=>window.__pulseStarts>0);
 const urgent=page.locator('[data-event-id="1"]').first(),soon=page.locator('[data-event-id="2"]').first(),ordinary=page.locator('[data-event-id="3"]').first();
 check(await urgent.getAttribute('data-calendar-deadline-level')==='urgent','previous-day event is urgent at '+width);check(await soon.getAttribute('data-calendar-deadline-level')==='soon','two-day event uses border-only state at '+width);check(await ordinary.getAttribute('data-calendar-deadline-level')==='','opt-out event stays ordinary at '+width);check(await page.evaluate(()=>window.__deadlineTimerCount())===1,'one pulse timer after initial display at '+width);
 await urgent.dispatchEvent('animationend');await sync();let pulses=await page.evaluate(()=>window.__pulseStarts);await page.evaluate(()=>window.__advance(30000));await page.evaluate(()=>{const days=document.querySelector('.calendar-days');days.replaceWith(days.cloneNode(true));});await sync();check(await page.evaluate(()=>window.__pulseStarts)===pulses,'card replacement does not restart cadence at '+width);check(await page.evaluate(()=>window.__deadlineTimerCount())===1,'card replacement keeps one pulse timer at '+width);
 await page.evaluate(()=>{window.__advance(29000);document.dispatchEvent(new Event('scroll',{bubbles:true}));});await sync();check(await page.evaluate(()=>window.__pulseStarts)===pulses,'no repeat before one minute at '+width);const beforeMinuteRequests=requests;await page.evaluate(()=>{window.__advance(1000);document.dispatchEvent(new Event('scroll',{bubbles:true}));});await page.waitForFunction(expected=>window.__pulseStarts>expected,pulses);pulses=await page.evaluate(()=>window.__pulseStarts);check(requests===beforeMinuteRequests,'one-minute pulse adds no API request at '+width);check(await page.evaluate(()=>window.__deadlineTimerCount())===1,'repeat pulse still has one timer at '+width);
 await page.locator('[data-event-id="1"]').first().dispatchEvent('animationend');await page.evaluate(()=>window.__advance(20000));await page.evaluate(()=>window.__setHidden(true));await sync();check(await page.evaluate(()=>window.__deadlineTimerCount())===0,'hidden tab pauses pulse timer at '+width);const hiddenPulses=await page.evaluate(()=>window.__pulseStarts);await page.evaluate(()=>{window.__advance(120000);document.dispatchEvent(new Event('scroll',{bubbles:true}));});await sync();check(await page.evaluate(()=>window.__pulseStarts)===hiddenPulses,'hidden tab does not pulse at '+width);await page.evaluate(()=>window.__setHidden(false));await sync();check(await page.evaluate(()=>window.__pulseStarts)===hiddenPulses,'return resumes remaining interval instead of immediate repeat at '+width);check(await page.evaluate(()=>window.__deadlineTimerCount())===1,'return recreates only one pulse timer at '+width);
 await page.evaluate(()=>{window.__advance(39000);document.dispatchEvent(new Event('scroll',{bubbles:true}));});await sync();check(await page.evaluate(()=>window.__pulseStarts)===hiddenPulses,'paused interval keeps remaining second at '+width);await page.evaluate(()=>{window.__advance(1000);document.dispatchEvent(new Event('scroll',{bubbles:true}));});await page.waitForFunction(expected=>window.__pulseStarts>expected,hiddenPulses);pulses=await page.evaluate(()=>window.__pulseStarts);check(true,'pulse resumes after one active minute at '+width);
 await page.locator('[data-event-id="1"]').first().dispatchEvent('animationend');await page.emulateMedia({reducedMotion:'reduce'});await sync();const reducedPulses=await page.evaluate(()=>window.__pulseStarts);await page.evaluate(()=>{window.__advance(60000);document.dispatchEvent(new Event('scroll',{bubbles:true}));});await sync();check(await page.evaluate(()=>window.__pulseStarts)===reducedPulses,'reduced motion suppresses repeat pulse at '+width);check(await page.evaluate(()=>window.__deadlineTimerCount())===0,'reduced motion disables pulse timer at '+width);
 await page.evaluate(()=>{window.__now=Date.parse('2026-10-11T00:00:00+09:00');document.dispatchEvent(new Event('scroll',{bubbles:true}));});await sync();check(await page.locator('[data-event-id="1"]').first().getAttribute('data-calendar-deadline-level')==='','deadline expiry returns to ordinary state at '+width);check(await page.locator('[data-event-id="1"]').first().evaluate(n=>getComputedStyle(n).boxShadow==='none'),'deadline expiry removes emphasis at '+width);check(errors.length===0,'no browser errors: '+errors.join(','));await context.close();
 }}finally{await browser.close();}console.log('RESULT: PASS '+checks+' / FAIL 0 / SKIP 0');})().catch(e=>{console.error(e);process.exitCode=1;});
