from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def t(r): return (ROOT/r).read_text(encoding='utf-8')
def c(ok,msg): checks.append((bool(ok),msg)); print(('PASS' if ok else 'FAIL')+': '+msg)
version=t('app/version.php'); loader=t('public/js/calendar.js'); streaming=t('public/js/camera-video-streaming.js')
ut=t('public/css/utility-widgets.css'); mcss=t('public/css/memo-refresh.css'); mjs=t('public/js/memo-refresh.js')
ccss=t('public/css/calendar-colors.css'); cjs=t('public/js/calendar-colors.js'); cphp=t('app/calendar_color.php'); cep=t('public/calendar_color_api.php'); ht=t('public/.htaccess'); mig=t('database/migrations/013_v1_20_1_calendar_event_color.sql'); schema=t('database/schema.sql'); mini=t('app/mini_game.php'); bjs=t('public/js/block-collapse.js'); bcss=t('public/css/block-collapse.css')
rb=t('tools/build_release_package.py'); rv=t('tools/verify_release_package.py'); cb=t('tools/build_complete_package.py'); cv=t('tools/verify_complete_package.py'); ci=t('.github/workflows/ci.yml'); wf=t('.github/workflows/v1.20.1-release.yml'); readme=t('README.md'); changelog=t('CHANGELOG.md'); notes=t('RELEASE_NOTES.md')
c("const APP_VERSION = '1.20.1';" in version,'APP_VERSION is exact V1.20.1'); c("const APP_VERSION_LABEL = 'RSS Reader Modernization 1.20.1';" in version,'visible label is exact V1.20.1'); c("const APP_ASSET_REVISION = '1.20.1';" in version,'asset revision is exact V1.20.1')
c('**Stable release:** `RSS Reader Modernization 1.20.1`' in readme and 'Release tag: `v1.20.1`' in readme,'README promotes V1.20.1'); c('## RSS Reader Modernization 1.20.1 — 2026-08-25' in changelog,'CHANGELOG contains V1.20.1 entry'); c(notes.startswith('# RSS Reader Modernization 1.20.1 Release Notes'),'release notes target V1.20.1')
c('.widget-drag-handle.widget-drag-handle::before' in ut and 'display: none !important' in ut,'Drag Handle runtime pseudo frame remains suppressed'); c('border: 1px solid currentColor !important' in ut and 'border-radius: 2px !important' in ut,'compact full Drag Handle box remains'); c('height: 48px;' in ut and 'min-height: 48px;' in ut,'Navbar remains compact at 48px'); c('@media (pointer: coarse)' in ut and '44px' in ut,'coarse-pointer touch target remains 44px')
c('overflow-y: auto;' in mcss and 'min-height: 0;' in mcss,'Memo body owns vertical scrolling'); c('[data-widget-height="2"]' in mcss and 'height: 648px' in mcss,'mobile Memo Height 2 is bounded'); c("action: 'widget.list'" in mjs,'Memo refresh reuses widget.list'); c('candidateWidgetId !== widgetId || candidateMemoId !== memoId' in mjs,'Memo refresh matches widget and memo ids'); c('window.confirm' in mjs and '保存していない編集内容' in mjs,'Memo unsaved edit confirmation remains'); c("$card.find('.memo-body').first().text(body)" in mjs,'Memo refresh writes body as text'); c('location.reload' not in mjs and 'setInterval(' not in mjs,'Memo refresh has no reload/polling')
c("['red', 'blue', 'green']" in cphp,'server Calendar color allowlist fixed'); c("var colorValues = ['red', 'blue', 'green'];" in cjs,'client Calendar color allowlist matches'); c("`calendar_event_color` VARCHAR(8) NOT NULL DEFAULT ''blue''" in mig,'migration adds blue-default Calendar color'); c('information_schema.COLUMNS' in mig and "COLUMN_NAME = 'calendar_event_color'" in mig,'Calendar color migration idempotent'); c("`calendar_event_color` VARCHAR(8) NOT NULL DEFAULT ''blue''" in schema,'fresh-install schema includes Calendar color'); c(all(x in cep for x in ['calendar.color.list','calendar.color.create','calendar.color.update']),'Calendar color endpoint has intended actions'); c('app_session_user_id()' in cep and 'app_csrf_is_valid' in cep and 'APP_API_MAX_REQUEST_BYTES' in cep and 'app_session_release();' in cep,'Calendar color endpoint keeps auth/CSRF/size/session boundary'); c('calendar_event_owner = :owner' in cphp,'Calendar color DB access remains owner scoped'); c('calendar_color_api\\.php' in ht and '.*\\.php$ - [F,L,NC]' in ht,'Public PHP matrix allows color endpoint and keeps deny-by-default'); c(all(x in ccss for x in ['.calendar-event-color-red','.calendar-event-color-blue','.calendar-event-color-green']),'Calendar red/blue/green CSS exists'); c(all(x in ccss for x in ['task-priority-high','task-priority-normal','task-priority-low']),'Task priority Calendar colors exist')
c("return ['icon_quest', 'lights_out', 'wire_defense', 'block_collapse'];" in mini,'Block Collapse is allowed Game subtype'); c('getContext' in bjs and "'2d'" in bjs,'Block Collapse uses Canvas 2D'); c('requestAnimationFrame' in bjs and 'cancelAnimationFrame' in bjs,'Block Collapse has bounded rAF lifecycle'); c('setInterval(' not in bjs,'Block Collapse has no interval loop'); c(all(x not in bjs for x in ['fetch(','XMLHttpRequest','$.ajax','api_v1.php']),'Block Collapse performs no network request'); c('localStorage' not in bjs and 'sessionStorage' not in bjs,'Block Collapse gameplay is not persisted'); c('BREAK_LIMIT = 8' in bjs,'Break limit retained'); c(all(x in bjs for x in ['STABILITY_MAX = 100','STABILITY_WARNING = 30','STABILITY_CRITICAL = 15','CRACK_STABILITY_COST = 3','DIRECT_BREAK_STABILITY_COST = 8','CHAIN_STABILITY_RECOVERY = 6']),'Stability tuning retained'); c('state.stability <= STABILITY_CRITICAL ? 70 : 40' in bjs,'Stability slip probabilities retained'); c('pointermove' in bjs and 'keydown' in bjs,'Block Collapse supports pointer/keyboard'); c('prefers-reduced-motion' in bcss,'Block Collapse respects reduced motion')
assets=['./css/mail-widget.css','./css/camera-video.css','./css/camera-video-playback.css','./css/camera-video-streaming.css','./css/x-widget.css','./css/memo-refresh.css','./css/calendar-colors.css','./css/block-collapse.css','./js/app-notice.js','./js/widget-card-refresh.js','./js/information-widget-watchdog.js','./js/memo-refresh.js','./js/calendar-colors.js','./js/block-collapse.js','./js/mail-widget-watchdog.js','./js/camera-video-watchdog.js','./js/mail-widget.js','./js/camera-video.js','./js/camera-video-playback.js','./js/camera-video-streaming.js','./js/x-widget.js','./js/widget-settings-no-reload.js']
for a in assets: c(a+'?v=1.20.1' in loader,'dynamic asset uses 1.20.1: '+a)
c('./css/camera-video-streaming.css?v=1.20.1' in streaming,'Camera fallback CSS uses 1.20.1'); c('1.20.1-d3' not in loader and '1.20.0-rc1' not in loader,'staged/old dynamic revisions absent')
c("INTENDED_RELEASE = '1.20.1'" in rb and "INTENDED_TAG = 'v1.20.1'" in rb,'Runtime builder targets 1.20.1'); c("metadata.get('intended_release') == '1.20.1'" in rv and "APP_VERSION = '1.20.1'" in rv,'Runtime verifier targets 1.20.1'); c("VERSION = '1.20.1'" in cb and 'intended_tag=v1.20.1' in cb,'Complete builder targets 1.20.1'); c("VERSION = '1.20.1'" in cv and '.github/workflows/v1.20.1-release.yml' in cv,'Complete verifier targets 1.20.1'); c('bash tests/run-v1201e.sh' in ci and 'bash tests/run-v120g.sh' not in ci,'CI uses 1.20.1 final gate'); c('V1.20.1 Release Gate' in wf and 'release/v1.20.1-final' in wf and 'bash tests/run-v1201e.sh' in wf,'Release workflow targets 1.20.1'); c('build_release_package.py --mode final' in wf and 'rss-reader-modernization-1.20.1-complete.zip' in wf,'Release workflow builds Runtime/Complete')
for r in ['APPLY_NOTE_V1_20_1.md','CHECKLIST_FOR_USER_V1_20_1.md','docs/v1-20-1-final-release.md','docs/v1-20-1-production-checklist.md','docs/v1-20-1-updated-files.md','docs/test-report-v1-20-1.md','V1_20_1_TEST_REPORT.md','UPDATED_FILES_V1_20_1.md']: c((ROOT/r).is_file(),'release document exists: '+r)
failed=[m for ok,m in checks if not ok]; print(f'RESULT: PASS {len(checks)-len(failed)} / FAIL {len(failed)} / SKIP 0'); raise SystemExit(1 if failed else 0)
