from pathlib import Path
import re, sys
ROOT=Path(__file__).resolve().parents[1]
calendar=(ROOT/'app/calendar.php').read_text(encoding='utf-8')
widget=(ROOT/'app/dashboard_widget.php').read_text(encoding='utf-8')
api=(ROOT/'app/api.php').read_text(encoding='utf-8')
bootstrap=(ROOT/'app/bootstrap.php').read_text(encoding='utf-8')
conf=(ROOT/'app/common/common_conf.php').read_text(encoding='utf-8')
index=(ROOT/'public/index.php').read_text(encoding='utf-8')
js=(ROOT/'public/js/calendar-core.js').read_text(encoding='utf-8')
css=(ROOT/'public/css/dashboard.css').read_text(encoding='utf-8')
version=(ROOT/'app/version.php').read_text(encoding='utf-8')
run=(ROOT/'tests/run.sh').read_text(encoding='utf-8')
checks=[]
def check(cond,msg): checks.append(bool(cond)); print(('PASS' if cond else 'FAIL')+': '+msg)
check("require_once __DIR__ . '/calendar.php';" in bootstrap, 'Calendar domain loads from the central bootstrap')
check("'calendar_event'" in conf and 'dashboard_widget' in conf and "'task'" in conf, 'Calendar event table is in the logical DB allowlist')
check("'calendar'" in widget.split('function dashboard_widget_types',1)[1].split('}',1)[0], 'Calendar is an allowed Dashboard Widget type')
check("'calendar' => calendar_widget_config_from_storage" in widget, 'Calendar Widget rows receive normalized config')
check("'title' => 'Calendar'" in calendar and "'show_completed_tasks' => false" in calendar, 'Calendar has restrained defaults')
check('calendar_widget_validate_title' in calendar and ', 32, false' in calendar, 'Calendar Widget title is bounded')
check('calendar_validate_year' in calendar and '>= 2000' in calendar and '<= 2100' in calendar, 'Calendar year is bounded')
check('calendar_validate_month' in calendar and '<= 12' in calendar, 'Calendar month is bounded')
check("DateTimeImmutable::createFromFormat('!Y-m-d'" in calendar, 'Calendar dates use exact ISO parsing')
check('> 365' in calendar, 'normal event duration is bounded to 366 inclusive days')
check('calendar_validate_event_title' in calendar and ', 128, false' in calendar, 'normal event title is bounded')
check('calendar_validate_event_note' in calendar and ', 2000, true' in calendar, 'normal event note is bounded')
check('calendar_normalize_event_row' in calendar, 'Calendar event DB rows pass one normalizer')
check('calendar_lock_owned_event' in calendar and 'calendar_event_owner = :owner' in calendar, 'Calendar event mutations use owner-scoped row lookup')
check('FOR UPDATE' in calendar, 'Calendar event writes lock rows on MySQL')
check(calendar.count('beginTransaction()') >= 3 and calendar.count('rollBack()') >= 3, 'Calendar event writes preserve rollback paths')
check('>= 500' in calendar and 'up to 500 active events' in calendar, 'active Calendar event count is bounded')
check('calendar_event_flag = 1' in calendar, 'Calendar event deletion is logical')
check('calendar_owned_widget_config' in calendar and "widget_type = 'calendar'" in calendar, 'month loading requires an owned active Calendar Widget')
check('calendar_month_data' in calendar and 'LIMIT 500' in calendar, 'month data is bounded')
check('calendar_event_start_date <= :month_end' in calendar and 'calendar_event_end_date >= :month_start' in calendar, 'multi-day normal events use overlap lookup')
check("FROM ' . db_table_identifier('task')" in calendar and "INNER JOIN ' . db_table_identifier('dashboard_widget')" in calendar, 'Task deadlines are read directly without duplication')
check("w.widget_type = 'task'" in calendar and 't.task_owner = :owner' in calendar, 'Task deadline lookup is owner and active Widget scoped')
check('t.task_due_date BETWEEN :month_start AND :month_end' in calendar, 'Task deadline lookup is month bounded')
check("if (!$showCompletedTasks)" in calendar and 't.task_completed = 0' in calendar, 'completed Task visibility follows Calendar Widget config')
check('dashboard_widget_create_calendar' in widget and 'dashboard_widget_update_calendar' in widget and 'dashboard_widget_delete_calendar' in widget, 'Calendar Widget CRUD is implemented in the domain layer')
check("VALUES (:owner, :location, 'calendar', NULL" in widget, 'Calendar Widget has no duplicated domain reference id')
check('widget_flag = 1' in widget[widget.find('function dashboard_widget_delete_calendar'):], 'Calendar Widget delete is logical')
for action in ['widget.calendar.create','widget.calendar.update','widget.calendar.delete','calendar.month.list','calendar.event.create','calendar.event.update','calendar.event.delete']:
    check(f"'{action}' =>" in api, f'{action} API action is registered')
check('calendar_create_event($userId' in api and 'calendar_month_data($userId' in api, 'Calendar ownership comes from authenticated user id')
segment=api[api.find('function api_widget_calendar_create'):api.find('function api_stock_create')]
check('calendar_event_owner' not in segment and 'widget_owner' not in segment, 'Calendar API never trusts a client owner field')
check("api_error('not_found'" in segment and "api_error('calendar_unavailable'" in segment, 'Calendar API has controlled not-found and DB failure responses')
check('data-dashboard-widget-type="calendar"' in index and 'calendar-card' in index, 'Calendar renders as a Dashboard Widget')
check('app_html($calendarTitle)' in index, 'Calendar Widget title is escaped at output')
check('calendar-month-label' in index and 'calendar-days' in index and 'role="grid"' in index, 'Calendar exposes a semantic month grid')
check('calendar-prev-month' in index and 'calendar-next-month' in index and 'calendar-today' in index, 'Calendar month navigation controls render')
check('id="registerCalendarWidgetForm"' in index and 'id="changeCalendarWidgetForm"' in index, 'Calendar Widget forms are explicit')
check('id="registerCalendarEventForm"' in index and 'id="changeCalendarEventForm"' in index, 'Calendar event forms are explicit')
check(index.count('type="date"') >= 4 and 'maxlength="128"' in index and 'maxlength="2000"' in index, 'Calendar event inputs are bounded and date based')
check('Calendar追加' in index and 'fa-calendar-alt' in index, 'Drawer exposes Calendar Widget addition')
check("app_asset_url('js/calendar.js')" in index, 'Calendar JavaScript is loaded as an external versioned asset')
check("var eventNamespace = '.iguguruCalendar';" in js, 'Calendar events use one namespace')
check("url: './api_v1.php'" in js and "'csrf_token': appCsrfToken()" in js, 'Calendar requests use the protected central API endpoint')
for action in ['widget.calendar.create','widget.calendar.update','widget.calendar.delete','calendar.month.list','calendar.event.create','calendar.event.update','calendar.event.delete']:
    check(f"apiRequest('{action}'" in js, f'Frontend sends {action}')
check('.html(' not in js and 'innerHTML' not in js and 'insertAdjacentHTML' not in js, 'Calendar JS keeps text-only DOM construction')
check(".append($('<span>').text(item.title))" in js, 'Calendar entry titles use text insertion')
check('guard < 370' in js, 'multi-day client expansion has a hard guard')
check('Math.ceil((firstDay + dayCount) / 7) * 7' in js, 'Calendar grid uses complete weeks')
check(js.count('changeCalendarWidget($(this));') == 1, 'Calendar Widget submit performs one update request')
check("window.confirm('このCalendar Widgetを削除しますか？ 登録済みの予定は残ります。')" in js, 'Calendar Widget deletion explains event preservation')
check("window.confirm('この予定を削除しますか？')" in js, 'Calendar event deletion has explicit confirmation')
check('.calendar-card' in css and '.calendar-card-inner' in css and '.calendar-card-body' in css, 'Calendar participates in Dashboard card layout')
check('.calendar-weekdays' in css and '.calendar-days' in css and 'grid-template-columns: repeat(7' in css, 'Calendar uses a seven-column grid')
check('.calendar-day-today' in css and '.calendar-task-entry.task-completed' in css, 'today and completed Tasks have restrained visual states')
check('@media (max-width: 767.98px)' in css and 'min-width: 500px' in css, 'Calendar has a deliberate narrow-screen fallback')
check((re.search(r"const APP_VERSION = '1\.1\.0-dev\.[89][0-9]*';", version) is not None and any(label in version for label in ['V1.1-I / R1','V1.1-I / R2','V1.1-J / R1'])) or ("const APP_VERSION = '1.1.0';" in version and 'RSS Reader Modernization 1.1.0' in version) or "const APP_VERSION = '1.2.0-dev.3';" or "const APP_VERSION = '1.2.0-dev.4';" in version, 'visible Version marker is V1.1-I or later')
check('test_v11i_calendar_widget.php' in run and 'test_v11i_frontend_runtime.js' in run, 'main regression runner includes V1.1-I checks')
if not all(checks):
    print(f'{sum(1 for x in checks if not x)}/{len(checks)} V1.1-I architecture checks failed')
    sys.exit(1)
print(f'All {len(checks)} V1.1-I architecture checks passed.')
