from pathlib import Path
import re, subprocess, sys
ROOT=Path(__file__).resolve().parents[1]
schema=(ROOT/'database/schema.sql').read_text(encoding='utf-8')
migration=(ROOT/'database/migrations/005_v1_1_task.sql').read_text(encoding='utf-8')
pre=(ROOT/'database/audit/v1_1_h_preflight.sql').read_text(encoding='utf-8')
post=(ROOT/'database/audit/v1_1_h_postflight.sql').read_text(encoding='utf-8')
tool=(ROOT/'tools/db_v11h.php').read_text(encoding='utf-8')
gitignore=(ROOT/'.gitignore').read_text(encoding='utf-8')
checks=[]
def check(cond,msg): checks.append(bool(cond)); print(('PASS' if cond else 'FAIL')+': '+msg)
check("SET @t_task = CONCAT('`', @table_prefix, 'task`');" in schema, 'new schema derives Task table from the configured prefix')
check("'CREATE TABLE ', @t_task" in schema, 'new installs create the Task table')
for col in ['task_id','task_date','task_updated_at','task_flag','task_owner','task_widget_id','task_title','task_due_date','task_priority','task_completed','task_completed_at','task_sort_order']:
    check(f'`{col}`' in schema and f'`{col}`' in migration, f'Task column {col} exists in schema and migration')
check('BIGINT UNSIGNED NOT NULL AUTO_INCREMENT' in migration, 'Task id uses an unsigned BIGINT')
check('task_due_date` DATE NULL' in migration, 'Task due date is optional')
check('ascii_bin' in migration and "DEFAULT ''normal''" in migration, 'Task priority has a stable ASCII representation')
check('idx_task_owner_widget_flag_order' in migration and 'task_sort_order' in migration, 'Task Widget listing has an owner-scoped order index')
check('idx_task_owner_due' in migration and 'task_completed' in migration, 'future Calendar lookup has an owner/due index')
check('CREATE TABLE IF NOT EXISTS' in migration, 'existing DB migration is idempotent')
check("SET @table_prefix = 'ig_';" in migration, 'manual migration makes prefix selection explicit')
check('FOREIGN KEY' not in migration.upper(), 'Task migration adds no foreign key to Legacy data')
check(all(word not in pre.upper() for word in ['INSERT ','UPDATE ','DELETE ','DROP ','ALTER ','CREATE ']), 'preflight is read-only')
check(all(word not in post.upper() for word in ['INSERT ','UPDATE ','DELETE ','DROP ','ALTER ','CREATE ']), 'postflight is read-only')
check('information_schema.COLUMNS' in post and 'information_schema.STATISTICS' in post, 'postflight reports columns and indexes')
check("widget_type = ''task''" in post and 'task_flag = 0' in post, 'postflight checks active Task and Widget consistency')
check('apply --backup-confirmed' in tool and 'verify is read-only' in tool, 'CLI separates apply and read-only verify')
check("db_table_name('task')" in tool and "db_table_identifier('task')" in tool, 'CLI uses safe prefixed identifiers')
check('information_schema.TABLES' in tool and 'SHOW COLUMNS' in tool and 'SHOW INDEX' in tool, 'CLI verifies table, columns and indexes')
check("Apply V1.1-D first" in tool, 'Task migration refuses a missing Widget foundation')
check('Active Task without active Task Widget' in tool, 'CLI checks orphan active Tasks')
check('!/database/migrations/005_v1_1_task.sql' in gitignore, 'Task migration is explicitly versionable')
check('!/database/audit/v1_1_h_preflight.sql' in gitignore and '!/database/audit/v1_1_h_postflight.sql' in gitignore, 'Task audit SQL is explicitly versionable')
proc=subprocess.run(['php',str(ROOT/'tools/db_v11h.php'),'--help'],cwd=ROOT,text=True,capture_output=True)
check(proc.returncode==0 and 'db_v11h.php verify' in proc.stdout, 'Task DB CLI help runs without DB access')
if not all(checks): sys.exit(1)
print(f'All {len(checks)} V1.1-H SQL checks passed.')
