'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..');
const rows=[1,2].map(id=>({widget_id:id,widget_owner:7,widget_location:0,widget_type:'game',widget_flag:0,widget_sort_order:id,widget_style:'primary',widget_width:1,widget_height:1,widget_config:JSON.stringify({schema:1,title:'Tower Defense',game:'tower_defense'}),widget_reference_id:null}));
const markup=execFileSync('php',[path.join(__dirname,'fixtures/widget_header_page.php'),JSON.stringify(rows)],{encoding:'utf8'});
const html='<!doctype html><html lang="ja"><head><meta charset="utf-8"><link rel="stylesheet" href="/css/bootstrap-5.3.8.min.css"><link rel="stylesheet" href="/css/game-widget.css"><link rel="stylesheet" href="/css/dashboard.css"></head><body>'+markup+'<script src="/js/game-widget.js?v=td-test"></script><script src="/js/mini-game.js"></script></body></html>';
let checks=0;function check(ok,name){assert(ok,name);checks++;console.log('PASS: '+name);}
(async()=>{const browser=await chromium.launch({executablePath:process.env.GAME_TEST_CHROME||chromium.executablePath(),headless:true,args:['--no-sandbox']});
try{for(const width of [1280,360]){
 const context=await browser.newContext({viewport:{width,height:1000},hasTouch:width<600}),requests=[],errors=[];
 await context.route('http://td.test/**',async route=>{let u=new URL(route.request().url());requests.push(u.pathname+u.search);if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:html});const file=path.join(root,'public',u.pathname);return fs.existsSync(file)?route.fulfill({body:fs.readFileSync(file),contentType:u.pathname.endsWith('.js')?'text/javascript':u.pathname.endsWith('.png')?'image/png':'text/css'}):route.fulfill({status:404,body:''});});
 await context.route('**/*',route=>new URL(route.request().url()).hostname==='td.test'?route.fallback():route.abort());
 await context.addInitScript(()=>{window.__rafTotal=0;const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>raf(t=>{window.__rafTotal++;fn(t);});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://td.test/');await page.waitForFunction(()=>document.querySelectorAll('.td-widget').length===2,{},{timeout:5000}).catch(async e=>{console.error('DIAGNOSTIC',errors,requests,await page.locator('#main-content').first().innerHTML());throw e;});
 const first=page.locator('.mini-game-card').nth(0),second=page.locator('.mini-game-card').nth(1);
 check(requests.filter(u=>u.startsWith('/js/tower-defense.js')).length===1,'one UI module for two widgets at '+width);
 check(requests.includes('/js/tower-defense-core.js?v=td-test'),'core inherits parent revision');
 check(await first.locator('.td-cell').count()===96,'actual PHP card mounts tap grid');
 await second.locator('.td-stage-select').selectOption('5');
 check(await second.locator('.td-cell[aria-label*=岩]').count()===12,'stage six exposes twelve rock cells');
 check(await second.locator('.td-cell[data-x="3"][data-y="1"]').isDisabled(),'rock rejects pointer placement');
 await page.evaluate(()=>{const key=RssGameWidget.storageKey(7,2,'tower_defense')+'.state',checkpoint=RssTowerDefenseCore.checkpoint(RssTowerDefenseCore.create(5));checkpoint.gold=160;checkpoint.towers=[{x:3,y:1,type:'bow',level:1,spent:60}];localStorage.setItem(key,JSON.stringify({schema:1,checkpoint,bests:[0,0,0,0,0,0]}));});
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.td-widget').length===2);
 await second.locator('.td-cell[data-x="3"][data-y="1"]').click();
 check(await second.locator('.td-upgrade').isEnabled(),'legacy tower on rock remains selectable and upgradeable');
 await second.locator('.td-sell').click();
 check(await second.locator('.td-cell[data-x="3"][data-y="1"]').isDisabled()&&await second.locator('.td-confirm').isDisabled(),'selling legacy tower does not allow rebuilding on rock');
 await second.locator('.game-widget-expand').click();await page.screenshot({path:'/tmp/rss-td-rocks-'+width+'.png'});await second.locator('.game-widget-expand').click();
 await first.locator('.td-cell[data-x="8"][data-y="3"]').click();await first.locator('[data-tower="bow"]').click();
 check(await first.locator('[data-td-stat=gold]').textContent()==='220G' && await first.locator('[data-td-stat=wave]').textContent()==='0/8','choosing tower does not place before confirmation');
 await first.locator('.td-confirm').click();check((await first.locator('.td-summary').textContent()).includes('160G'),'confirm deducts tower cost');
 check((await second.locator('.td-summary').textContent()).includes('205G'),'other widget remains independent');
 await first.locator('.td-upgrade').click();check((await first.locator('.td-selection').textContent()).includes('Lv.2'),'tap upgrade');
 await first.locator('.td-cell[data-x="1"][data-y="1"]').click();await first.locator('[data-tower="bow"]').click();await first.locator('.td-confirm').click();
 await page.evaluate(()=>{window.__tdHitSeen=false;const step=RssTowerDefenseCore.step;RssTowerDefenseCore.step=function(state,dt){step(state,dt);window.__tdActiveHit=state.enemies.some(e=>e.hitFlash>0);if(state.shots.some(s=>s.hits&&s.hits.length)&&state.enemies.some(e=>e.hitFlash>0))window.__tdHitSeen=true;};});
 const key=await page.evaluate(()=>RssGameWidget.storageKey(7,1,'tower_defense')+'.state');const before=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
 check(before.checkpoint.towers[0].level===2,'preparation checkpoint stored');
 await first.locator('.td-next').click();await page.waitForTimeout(400);check(await first.getAttribute('data-game-widget-status')==='fight','explicit wave starts fight');
 check(await page.evaluate(()=>window.__tdHitSeen),'actual wave produces damage and hit feedback');
 check(await first.locator('.td-upgrade').isDisabled()&&await first.locator('.td-sell').isDisabled(),'fight prevents economy changes');
 await page.waitForFunction(()=>window.__tdActiveHit);
 await first.locator('.game-widget-pause').click();check(await first.locator('.game-widget-pause').getAttribute('aria-pressed')==='true','manual pause');
 await first.locator('.game-widget-expand').click();await page.screenshot({path:'/tmp/rss-td-impact-'+width+'.png'});await page.emulateMedia({reducedMotion:'reduce'});await first.locator('.game-widget-expand').click();await first.locator('.game-widget-expand').click();await page.screenshot({path:'/tmp/rss-td-impact-reduced-'+width+'.png'});await first.locator('.game-widget-expand').click();await page.emulateMedia({reducedMotion:'no-preference'});
 const during=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);check(JSON.stringify(during.checkpoint)===JSON.stringify(before.checkpoint),'wave leaves preceding preparation checkpoint');
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.td-widget').length===2);
 check(await first.getAttribute('data-game-widget-status')==='prepare','mid-wave reload returns to preparation');
 await first.locator('.td-cell[data-x="8"][data-y="3"]').click();check((await first.locator('.td-selection').textContent()).includes('Lv.2'),'reload restores upgraded placement');
 await first.locator('.game-widget-expand').click();check(await first.locator('.mini-game-card-inner').getAttribute('aria-modal')==='true','uses existing expansion dialog');
 check(await first.locator('.td-board').evaluate(n=>n.getBoundingClientRect().width<=541),'expanded board matches bounded existing Game sizing');
 check(await first.locator('.td-confirm').evaluate(n=>n.getBoundingClientRect().height>=44),'TD action buttons keep existing 44px target');
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no page overflow at '+width);
 await page.screenshot({path:'/tmp/rss-td-'+width+'.png'});
 for(const theme of ['bootstrap-flatly','bootstrap-solar','bootstrap-slate','bootstrap']){
  const themeStyle=await page.addStyleTag({content:fs.readFileSync(path.join(root,'public/css/'+theme+'-5.3.8.min.css'),'utf8').replace(/@import[^;]*;/g,'')});
  await page.evaluate(theme=>{document.querySelector('#main-content').dataset.dashboardTheme=theme;},theme);
  // Resize through the existing expanded-view control redraws the canvas.
  await first.locator('.game-widget-expand').click();await first.locator('.game-widget-expand').click();
  check(await first.locator('.td-board').evaluate(n=>getComputedStyle(n).backgroundColor===getComputedStyle(n.closest('.td-widget')).getPropertyValue('--bs-body-bg').trim() || getComputedStyle(n).backgroundColor===getComputedStyle(document.body).backgroundColor),'neutral TD surface follows '+theme+' at '+width);
  await page.screenshot({path:'/tmp/rss-td-'+theme+'-'+width+'.png'});
  await themeStyle.evaluate(n=>n.remove());
 }
 check(!requests.some(u=>u.startsWith('/assets/td/')),'line renderer needs no bitmap assets');
 await first.press('Escape');check(await first.locator('.game-widget-expand').getAttribute('aria-expanded')==='false','Escape closes expanded view');
 const baseKey=key.slice(0,-6);await page.evaluate(()=>RssGameWidget.removeWidgetState(1));check(await page.evaluate(k=>localStorage.getItem(k)===null,key),'widget deletion removes its checkpoint');
 check(await page.evaluate(()=>!!localStorage.getItem(RssGameWidget.storageKey(7,2,'tower_defense')+'.state')),'deletion preserves other widget');
 await first.locator('.td-next').click();await page.waitForTimeout(200);await first.evaluate(n=>n.remove());await page.waitForTimeout(100);const stopped=await page.evaluate(()=>window.__rafTotal);await page.waitForTimeout(200);check(await page.evaluate(()=>window.__rafTotal)===stopped,'removing fighting widget stops animation loop');
 check(errors.length===0,'no browser exceptions: '+errors.join(','));await context.close();
}
}finally{await browser.close();}console.log('RESULT: PASS '+checks+' / FAIL 0 / SKIP 0');})().catch(e=>{console.error(e);process.exitCode=1;});
