'use strict';
// Optional focused gate: production PHP Drawer fragments, local JS/CSS, isolated API fixtures.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..');let checks=0;
function check(ok,name){assert.ok(ok,name);checks++;console.log('PASS: '+name);}
function nav(source){
 const php=`function app_html($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function app_csrf_token(){return 'fixture-csrf';}$ui=[];for($i=1;$i<=4;$i++){$ui['conf_style_tabname'.$i]='タブ'.$i;$ui['conf_style_navlink'.$i]='';$ui['conf_style_navlink_icon'.$i]='link';$ui['conf_style_navlink_view'.$i]='';}$ui['conf_style_navlink1']='https://example.invalid/';$ui['conf_style_navlink_view1']='利用者リンク';$ui['conf_style_navlink2']='./settings#tabs';$ui['conf_style_navlink_view2']='設定への利用者リンク';$tabParam=basename($argv[1])==='stock.php'?'stock':0;$src=file_get_contents($argv[1]);$start=strpos($src,'<nav class="offcanvas offcanvas-end drawer-nav"');$end=strpos($src,'</nav>',$start)+6;eval('?>'.substr($src,$start,$end-$start));`;
 return execFileSync(process.env.PHP_BINARY||'php',['-r',php,path.join(root,'public',source)],{encoding:'utf8'});
}
const modules=['game-widget','mini-game','lights-out','cursor-field','game-2048','reversi','dashboard-core','dashboard','utility-widgets','clock-timer','connection-monitor','all-rss-recent','info-board','mail-widget','camera-video','x-widget','block-collapse'];
function html(source,theme){
 const dashboard=['index.php','stock.php'].includes(source),modal=fs.readFileSync(path.join(root,source==='stock.php'?'public/stock.php':'app/view/dashboard_modals.php'),'utf8'),select=modal.match(/<select\b[^>]*\bid="registerGameType"[^>]*>[\s\S]*?<\/select>/)[0];
 const modals=['registerContent','registerSearchFeed','registerTaskWidget','registerCalendarWidget','registerLinksWidget','registerWeatherWidget','registerClock','registerMemo','accountSettings'].map(id=>`<div id="${id}" class="modal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><button data-bs-dismiss="modal">閉じる</button></div></div></div>`).join('');
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="fixture-csrf"><link rel="stylesheet" href="/css/${theme}"><link rel="stylesheet" href="/css/all.css"><link rel="stylesheet" href="/css/dashboard.css"></head><body><button id="openDrawer" class="drawer-toggle" aria-controls="drawerMenu" aria-expanded="false" data-bs-toggle="offcanvas" data-bs-target="#drawerMenu">Menu</button>${nav(source)}${modals}<div class="modal" id="registerGameWidget" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form id="registerGameWidgetForm">${select}<input class="registerGameTitleValue" value="Icon Quest"><button type="button" data-bs-dismiss="modal">閉じる</button></form></div></div></div><div id="main-content" data-dashboard-user-id="7" data-dashboard-current-tab="${source==='stock.php'?'':'0'}"></div><button id="outside">外側</button><div style="height:2000px"></div><script src="/js/jquery-3.7.1.min.js"></script><script src="/js/bootstrap.bundle-5.3.8.min.js"></script>${(dashboard?modules:['dashboard-core','dashboard']).map(m=>`<script src="/js/${m}.js?v=fixture-revision"></script>`).join('')}</body></html>`;
}
function snapshot(){const d=document.getElementById('drawerMenu');return {actions:Array.from(d.querySelectorAll('[data-drawer-modal-target]')).map(n=>[n.getAttribute('data-drawer-modal-target'),n.getAttribute('data-game-preset'),n.disabled,n.textContent.trim()]).sort(),links:Array.from(d.querySelectorAll('a[href]')).map(n=>[n.getAttribute('href'),n.getAttribute('aria-current'),n.getAttribute('target'),n.getAttribute('rel')]).sort(),form:d.querySelector('.drawer-logout-form').outerHTML};}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.GAME_TEST_CHROME||chromium.executablePath(),headless:true,args:['--no-sandbox']});
 try{
 const cases=[['index.php',1280,'bootstrap-5.3.8.min.css'],['index.php',360,'bootstrap-5.3.8.min.css'],['stock.php',360,'bootstrap-5.3.8.min.css'],['settings.php',360,'bootstrap-5.3.8.min.css'],['file-library.php',1280,'bootstrap-5.3.8.min.css'],['remote-files.php',360,'bootstrap-5.3.8.min.css'],['rss-management.php',360,'bootstrap-5.3.8.min.css'],['index.php',320,'bootstrap-slate-5.3.8.min.css'],['index.php',768,'bootstrap-solar-5.3.8.min.css'],['index.php',1440,'bootstrap-flatly-5.3.8.min.css']];
 for(const [source,width,theme] of cases.filter(c=>!process.env.DRAWER_TEST_SOURCE||c[0]===process.env.DRAWER_TEST_SOURCE)){
 const context=await browser.newContext({viewport:{width,height:900},hasTouch:width<600}),errors=[],requests=[];
 await context.route('**/*',async route=>{const url=new URL(route.request().url());requests.push(url.pathname+url.search);if(url.hostname!=='drawer.test')return route.abort();if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:html(source,theme)});if(url.pathname==='/api_v1.php')return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,data:{widgets:[],items:[],feeds:[],events:[],entries:[],calendars:[]}})});const file=path.join(root,'public',url.pathname);if(!fs.existsSync(file)||!fs.statSync(file).isFile())return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(file),contentType:url.pathname.endsWith('.js')?'text/javascript':url.pathname.endsWith('.css')?'text/css':url.pathname.endsWith('.woff2')?'font/woff2':'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));console.log('CASE: '+source+'/'+width);await page.goto('http://drawer.test/',{waitUntil:'domcontentloaded'});const dashboard=['index.php','stock.php'].includes(source);
 if(dashboard){await page.waitForTimeout(150);await page.waitForFunction(()=>document.querySelectorAll('#widgetCatalog-game [data-game-preset]').length===11,{},{timeout:15000});}await page.waitForTimeout(100);
 const before=await page.evaluate(snapshot);
 await page.evaluate(()=>{window.__logout=document.querySelector('.drawer-logout-form');window.__probe=document.querySelector('[data-drawer-modal-target]');if(window.__probe)window.__probe.addEventListener('drawer-fixture-probe',()=>window.__probeCalls=(window.__probeCalls||0)+1);});
 await page.addScriptTag({url:'/js/drawer-categories.js?v=fixture-revision'});await page.waitForSelector('[data-drawer-categories]',{state:'attached'});await page.waitForFunction(()=>Array.from(document.styleSheets).some(s=>s.href&&s.href.includes('drawer.css')));
 const after=await page.evaluate(snapshot),tag=source+'/'+width;
 check(JSON.stringify(before.actions)===JSON.stringify(after.actions),'all original actions / presets / disabled states retained: '+tag);
 check(before.links.filter(x=>!['./settings#tabs','./settings#display','./settings#highlight'].includes(x[0])).every(x=>after.links.some(y=>JSON.stringify(x)===JSON.stringify(y))),'original URLs / current-page / external-link protection retained: '+tag);
 check(before.form===after.form&&await page.evaluate(()=>window.__logout===document.querySelector('.drawer-logout-form')),'logout POST / CSRF / node identity preserved: '+tag);
 check(await page.evaluate(()=>{if(!window.__probe)return true;window.__probe.dispatchEvent(new Event('drawer-fixture-probe'));return window.__probeCalls===1;}),'existing action listeners retained: '+tag);
 check(await page.locator('[data-drawer-section="other"]').count()===0,'known items avoid Other: '+tag);
 check(requests.includes('/css/drawer.css?v=fixture-revision'),'Drawer CSS inherits asset revision: '+tag);
 check(await page.locator('#drawerMenu li:not(.drawer-mobile-links) > a[href="./settings"]').count()===1&&await page.locator('#drawerMenu li:not(.drawer-mobile-links) > a[href^="./settings#"]').count()===0,'one unified Settings entry: '+tag);
 check(before.links.filter(x=>x[0]==='./settings#tabs').length<=1||await page.locator('#drawerMenu .drawer-mobile-links a[href="./settings#tabs"]').count()===1,'configured legacy Settings user link retained: '+tag);
 const groups=await page.locator('[data-drawer-section]').evaluateAll(ns=>ns.map(n=>n.dataset.drawerSection));
 check(groups.join(',')===(dashboard?'display,widgets,files,settings,user-links,account':source==='settings.php'?'display,files,settings,user-links,account':'display,files,settings,account'),'section order / empty groups match page capabilities: '+tag);
 await page.locator('#openDrawer').click();await page.waitForSelector('#drawerMenu.show');
 if(dashboard){
 check((await page.locator('[data-widget-catalog-category]').evaluateAll(ns=>ns.map(n=>n.dataset.widgetCatalogCategory))).join(',')==='rss,information,utility,media,game','five Widget categories in planned order: '+tag);
 check(await page.locator('#drawerMenu .collapse.show').count()===0,'catalog starts compact: '+tag);
 for(const id of ['rss','information','utility','media','game']){const toggle=page.locator(`[data-widget-catalog-category="${id}"] > button`);if(id==='utility'){await toggle.focus();await page.keyboard.press('Enter');}else{await toggle.click();}await page.waitForSelector('#widgetCatalog-'+id+'.show');check(await toggle.getAttribute('aria-expanded')==='true','accessible category opening: '+id+'/'+tag);check(await toggle.evaluate(n=>{const r=n.getBoundingClientRect(),a=n.querySelector('.widget-catalog-chevron').getBoundingClientRect(),d=document.getElementById('drawerMenu').getBoundingClientRect();return r.height>=44&&a.width>=17&&a.left>=r.left&&a.right<=r.right-8&&r.right<=d.right;}),'arrow / touch target inside Drawer: '+id+'/'+tag);check(await toggle.evaluate(n=>getComputedStyle(n).color==='rgb(73, 80, 87)'&&getComputedStyle(n).textDecorationLine==='none'),'readable category color / no underline: '+id+'/'+tag);}
 check(await page.locator('#widgetCatalog-media [data-drawer-modal-target="#registerCameraVideo"]').count()===1,'Camera / Video remains one Media entry: '+tag);
 check(await page.evaluate(()=>{const d=document.getElementById('drawerMenu');return d.scrollWidth<=d.clientWidth+1;}),'expanded catalog has no horizontal overflow: '+tag);
 if(source==='index.php'&&width===360){await page.screenshot({path:'/tmp/drawer-dev1-mobile.png'});await page.locator('[data-widget-catalog-category="rss"] .drawer-item-label').first().evaluate(n=>n.textContent='非常に長いカテゴリ名を表示した場合の確認');await page.evaluate(()=>document.documentElement.style.fontSize='32px');check(await page.locator('[data-widget-catalog-category="rss"] > button').evaluate(n=>{const r=n.getBoundingClientRect(),a=n.querySelector('.widget-catalog-chevron').getBoundingClientRect();return a.right<=r.right-8&&a.left>=r.left;}),'long category / 200% text keeps arrow visible');check(await page.evaluate(()=>{const d=document.getElementById('drawerMenu');return d.scrollWidth<=d.clientWidth+1;}),'200% text / expanded groups avoid horizontal overflow');await page.evaluate(()=>document.documentElement.style.fontSize='16px');}
 if(source==='index.php'&&width===1280){await page.locator('#drawerMenu').evaluate(n=>n.scrollTop=0);await page.screenshot({path:'/tmp/drawer-dev1-desktop.png'});}
 await page.keyboard.press('Escape');await page.waitForSelector('#drawerMenu.show',{state:'hidden'});await page.locator('#openDrawer').click();await page.waitForSelector('#drawerMenu.show');await page.locator('#widgetCatalog-media [data-drawer-modal-target="#registerCameraVideo"]').click();await page.waitForSelector('#registerCameraVideo.show');await page.waitForFunction(()=>document.getElementById('registerCameraVideo').contains(document.activeElement));check(await page.locator('.offcanvas-backdrop').count()===0&&await page.locator('.modal-backdrop').count()===1,'Media modal has exactly one backdrop: '+tag);await page.keyboard.press('Escape');await page.waitForSelector('#registerCameraVideo.show',{state:'hidden'});
 if(source==='index.php'&&[1280,360].includes(width)){for(const type of ['icon_quest','lights_out','wire_defense','block_collapse','cursor_field','game_2048','reversi','maze_chase','falling_blocks','word_tiles','word_tiles_ja']){await page.locator('#openDrawer').click();await page.waitForSelector('#drawerMenu.show');await page.locator('#widgetCatalog-game [data-game-preset="'+type+'"]').click();await page.waitForSelector('#registerGameWidget.show');await page.waitForFunction(()=>document.getElementById('registerGameWidget').contains(document.activeElement));check(await page.inputValue('#registerGameType')===type,'Game menu selects subtype: '+type+'/'+tag);await page.keyboard.press('Escape');await page.waitForSelector('#registerGameWidget.show',{state:'hidden'});}}
 }else{await page.keyboard.press('Escape');await page.waitForSelector('#drawerMenu.show',{state:'hidden'});}
 await page.waitForFunction(()=>!document.querySelector('.offcanvas-backdrop,.modal-backdrop'));check(await page.locator('.offcanvas-backdrop,.modal-backdrop').count()===0,'all backdrops removed after close: '+tag);check(await page.locator('#openDrawer').getAttribute('aria-expanded')==='false','menu trigger returns closed: '+tag);check(!requests.some(x=>/\/(maze-chase|falling-blocks|word-tiles)\.js/.test(x)),'menus do not load game engines: '+tag);
 const beforeRepeat=await page.evaluate(snapshot);await page.addScriptTag({url:'/js/drawer-categories.js?v=fixture-revision'});await page.waitForTimeout(60);check(JSON.stringify(beforeRepeat)===JSON.stringify(await page.evaluate(snapshot)),'organization is idempotent: '+tag);check(await page.locator('link[data-drawer-style]').count()===1,'no duplicate Drawer stylesheet: '+tag);check(errors.length===0,'no browser exceptions: '+tag+' '+errors.join(';'));await context.close();
 }
 console.log(`RESULT: PASS ${checks} / FAIL 0 / SKIP 0`);
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exit(1);});
