'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const window={RssGameWidget:{register(game,factory){assert.equal(game,'falling_blocks');assert.equal(typeof factory,'function');}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/js/falling-blocks.js'),'utf8'),{window,document:{},Math,Number,Object,Array});
const a=window.RssFallingBlocks;let checks=0;
function check(name,fn){fn();checks++;console.log('PASS: '+name);}
function state(){let s=a.createState(()=>.3);s.status='playing';return s;}
function cells(s){return s.board.flat().filter(Boolean).length;}
function valid(s){assert.equal(s.board.length,a.height);s.board.forEach(r=>{assert.equal(r.length,a.width);r.forEach(v=>assert.ok(Number.isInteger(v)&&v>=0&&v<=7));});assert.ok(Number.isSafeInteger(s.score)&&s.score>=0);assert.equal(s.level,1+Math.floor(s.lines/8));if(s.status==='playing')assert.ok(a.fits(s,s.active.matrix,s.active.x,s.active.y));}
check('seven distinct pieces each contain four cells',()=>{assert.equal(a.shapes.length,7);assert.equal(new Set(a.shapes.map(m=>JSON.stringify(m))).size,7);a.shapes.forEach(m=>{assert.equal(m.flat().filter(Boolean).length,4);assert.ok(m.every(r=>r.length===m.length));});});
check('bags contain all seven pieces and tolerate RNG boundaries',()=>{for(const rng of [()=>0,()=>1,()=>NaN,()=>-.5,()=>.99999])assert.equal([...a.bag(rng)].sort().join(','),'0,1,2,3,4,5,6');});
check('two successive bags stay complete during spawning',()=>{let s=state(),types=[];for(let i=0;i<14;i++){types.push(s.active.type);s.board.forEach(r=>r.fill(0));a.hardDrop(s);}assert.equal(types.slice(0,7).sort().join(','),'0,1,2,3,4,5,6');assert.equal(types.slice(7).sort().join(','),'0,1,2,3,4,5,6');});
check('instances own independent boards, queues and matrices',()=>{let x=state(),y=state();x.board[0][0]=1;x.active.matrix[0][0]=9;x.queue.length=0;assert.equal(y.board[0][0],0);assert.notEqual(y.active.matrix[0][0],9);assert.ok(y.queue.length);});
check('ready and ended states reject movement, rotation and drops',()=>{for(const status of ['ready','gameover']){let s=state();s.status=status;const before=JSON.stringify(s);a.move(s,1);a.rotate(s,true);a.drop(s,true);a.hardDrop(s);a.lock(s);assert.equal(JSON.stringify(s),before);}});
check('horizontal movement stops at occupied cells and both walls',()=>{let s=state();while(a.move(s,-1)){}let left=s.active.x;assert.equal(a.move(s,-1),false);assert.equal(s.active.x,left);while(a.move(s,1)){}assert.equal(a.move(s,1),false);assert.ok(a.fits(s,s.active.matrix,s.active.x,s.active.y));assert.equal(a.move(s,100),false);});
check('fit rejects walls, floor and overlapping cells',()=>{let s=state();assert.equal(a.fits(s,[[1]],-1,0),false);assert.equal(a.fits(s,[[1]],10,0),false);assert.equal(a.fits(s,[[1]],0,18),false);assert.equal(a.fits(s,[[1]],0,-1),false);s.board[1][1]=2;assert.equal(a.fits(s,[[1]],1,1),false);});
check('four rotations and inverse rotation restore each shape',()=>{a.shapes.forEach((shape,type)=>{let s=state();s.active={type,matrix:shape.map(r=>r.slice()),x:3,y:5};const before=JSON.stringify(s.active);for(let i=0;i<4;i++)assert.equal(a.rotate(s,true),true);assert.equal(JSON.stringify(s.active),before);a.rotate(s,true);a.rotate(s,false);assert.equal(JSON.stringify(s.active),before);});});
check('simple wall offset permits rotation beside a wall',()=>{let s=state();s.active={type:0,matrix:[[0,0,1,0],[0,0,1,0],[0,0,1,0],[0,0,1,0]],x:-2,y:3};assert.ok(a.fits(s,s.active.matrix,-2,3));assert.ok(a.rotate(s,true));assert.ok(a.fits(s,s.active.matrix,s.active.x,s.active.y));});
check('blocked rotation leaves original matrix and position intact',()=>{let s=state();s.active={type:2,matrix:a.shapes[2].map(r=>r.slice()),x:3,y:6};s.board.forEach((row,y)=>row.fill(y>=4&&y<=10?1:0));s.active.matrix.forEach((row,r)=>row.forEach((v,c)=>{if(v)s.board[6+r][3+c]=0;}));const before=JSON.stringify(s.active);assert.equal(a.rotate(s,true),false);assert.equal(JSON.stringify(s.active),before);});
check('gravity movement scores zero and soft drop scores one',()=>{let s=state();assert.ok(a.drop(s,false));assert.equal(s.score,0);assert.ok(a.drop(s,true));assert.equal(s.score,1);});
check('hard drop scores distance, locks four cells and advances once',()=>{let s=state(),next=s.next,queue=s.queue.length;let d=a.hardDrop(s);assert.ok(d>0);assert.equal(s.score,d*2);assert.equal(cells(s),4);assert.equal(s.active.type,next);assert.equal(s.queue.length,queue-1);valid(s);});
check('soft drop locks immediately at the floor without extra points',()=>{let s=state();while(a.fits(s,s.active.matrix,s.active.x,s.active.y+1))a.drop(s,false);const next=s.next;assert.equal(a.drop(s,true),false);assert.equal(s.score,0);assert.equal(cells(s),4);assert.equal(s.active.type,next);});
for(let n=1;n<=4;n++)check(n+' lines clear with compacted rows and level-scaled score',()=>{let s=state();s.level=2;s.lines=8;for(let y=18-n;y<18;y++){s.board[y].fill(2);s.board[y][4]=0;}s.active={type:0,matrix:[[0,1,0,0],[0,1,0,0],[0,1,0,0],[0,1,0,0]],x:3,y:14};a.lock(s);assert.equal(s.lines,8+n);assert.equal(s.score,[0,100,260,460,720][n]*2);assert.equal(cells(s),4-n);assert.ok(s.board.slice(0,n).every(r=>r.every(v=>v===0)));valid(s);});
check('eighth cleared line increases level and gravity speed',()=>{let s=state();s.lines=7;s.board[17].fill(1);s.board[17][4]=0;s.active={type:0,matrix:[[1]],x:4,y:17};let before=a.gravity(s);a.lock(s);assert.equal(s.level,2);assert.equal(s.lines,8);assert.ok(a.gravity(s)<before);s.level=100;assert.equal(a.gravity(s),90);});
check('blocked spawn ends game without overwriting locked cells',()=>{let s=state();s.board[0].fill(3,1,9);s.board[1].fill(3,1,9);s.active.y=10;a.hardDrop(s);assert.equal(s.status,'gameover');assert.ok(s.board[0].slice(1,9).every(v=>v===3));let before=JSON.stringify(s);a.hardDrop(s);assert.equal(JSON.stringify(s),before);});
check('supported keys are explicit and unrelated keys are ignored',()=>{for(const k of ['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','x','X','z','Z'])assert.ok(a.keyAction(k));for(const k of ['Tab','Escape','Enter','w','constructor'])assert.equal(a.keyAction(k),null);});
check('100 long seeded simulations preserve bounds and valid settled cells',()=>{for(let seed=1;seed<=100;seed++){let n=seed,rng=()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296;},s=a.createState(rng);s.status='playing';for(let i=0;i<2000&&s.status==='playing';i++){const v=rng();if(v<.25)a.move(s,-1);else if(v<.5)a.move(s,1);else if(v<.65)a.rotate(s,true);else if(v<.8)a.rotate(s,false);else if(v<.95)a.drop(s,true);else a.hardDrop(s);valid(s);}}});
console.log('RESULT: PASS '+checks+' / FAIL 0 / SKIP 0');
