'use strict';
const fs=require('fs'); const path=require('path');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'public/js/dashboard.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.php'),'utf8');
const css=fs.readFileSync(path.join(root,'public/css/dashboard.css'),'utf8');
let checks=0,failures=0;
function check(cond,msg){checks++;console.log((cond?'PASS':'FAIL')+': '+msg);if(!cond)failures++;}
check(js.includes('function taskWidgetFormPayload(prefix)'), 'Task Widget payload helper exists');
check(js.includes("'task_widget_title': $('.' + prefix + 'TaskWidgetTitleValue').val()"), 'Task Widget title is read from a form value');
check(js.includes("apiRequest('widget.task.create', payload, 3000)"), 'Task Widget create uses central API helper');
check(js.includes("apiRequest('widget.task.update', payload, 3000)"), 'Task Widget update uses central API helper');
check(js.includes("apiRequest('widget.task.delete', {'widget_id': widgetId}, 3000)"), 'Task Widget delete sends only Widget ID');
check(js.includes('function taskItemPayload($scope)'), 'Task item payload helper exists');
check(js.includes("'task_title': $scope.find('.task-create-title, .changeTaskItemTitleValue').first().val()"), 'Task item title comes from form controls');
check(js.includes("'task_due_date': $scope.find('.task-create-due, .changeTaskItemDueDate').first().val()"), 'Task due date comes from date controls');
check(js.includes("'task_priority': $scope.find('.task-create-priority, .changeTaskItemPriority').first().val()"), 'Task priority comes from select controls');
for (const action of ['task.item.create','task.item.update','task.item.toggle','task.item.delete']) check(js.includes(`apiRequest('${action}'`), `${action} uses central API helper`);
check(js.includes("'task_completed': completed ? '0' : '1'"), 'Task completion explicitly toggles 0 and 1');
check(js.includes("payload.widget_id = String($form.attr('data-widget-id') || '')"), 'Task create remains scoped to its Widget');
check(js.includes("payload.task_id = $('.changeTaskItemId').val()"), 'Task update sends selected Task ID');
check(js.includes("window.confirm('このTask Widgetと中のTaskを削除しますか？')"), 'Task Widget deletion confirms cascade');
check(js.includes("window.confirm('このTaskを削除しますか？')"), 'Task item deletion confirms');
for (const selector of ['#registerTaskWidgetForm','.task-widget-edit-trigger','#changeTaskWidgetForm','.delete_task_widget','.task-item-create-form','.task-item-edit-trigger','#changeTaskItemForm','.task-toggle','.delete_task_item']) check(js.includes(`.off('`) && js.includes(selector), `Task handler is present for ${selector}`);
check((js.match(/\.always\(function \(\)/g)||[]).length>=15, 'Task mutations release pending state through always');
check(!js.includes('.html('), 'Dashboard JS keeps text-only DOM operations');
check(html.includes('id="registerTaskWidgetForm"')&&html.includes('id="changeTaskWidgetForm"')&&html.includes('id="changeTaskItemForm"'), 'Task forms are present');
check(html.includes('maxlength="128"')&&html.includes('type="date"'), 'Task inputs are bounded');
check(html.includes('data-dashboard-widget-type="task"'), 'Task card exposes its Widget type');
check(html.includes('app_html($taskTitle)'), 'Task title is escaped before output');
check(css.includes('.task-completed .task-item-title')&&css.includes('line-through'), 'completed Task style is restrained');
check(css.includes('.task-create-options')&&css.includes('grid-template-columns'), 'Task create controls use bounded grid layout');
if(failures)process.exit(1);
console.log(`All ${checks} V1.1-H frontend checks passed.`);
