'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const window={RssGameWidget:{register(game,factory){assert.equal(game,'word_tiles');assert.equal(typeof factory,'function');}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/js/word-tiles-words-en.js'),'utf8'),{window,Object});
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/js/word-tiles.js'),'utf8'),{window,document:{},Math,Number,Object,Array,Set,JSON});
const a=window.RssWordTiles;let count=0;
function check(name,fn){fn();count++;console.log('PASS: '+name);}
function state(){let s=a.createState(()=>.5);s.status='playing';return s;}
function cat(s){a.place(s,39,0);a.place(s,40,1);a.place(s,41,2);return a.submit(s);}
function inventory(s){return s.board.concat(s.rack,s.pool).filter(Boolean).sort().join('');}
check('starter dictionary is unique, uppercase and contains only 2-9 letter words',()=>{assert.equal(new Set(a.words).size,a.words.length);a.words.forEach(w=>assert.match(w,/^[A-Z]{2,9}$/));for(const word of ['CAT','CAR','AT','ART','TREE','WORD','TILES'])assert.ok(a.words.includes(word));});
check('expanded dictionary preserves every C1 word and includes new common words',()=>{const starter=fs.readFileSync(path.join(__dirname,'fixtures/word-tiles/starter-en.txt'),'utf8').trim().split(/\s+/);starter.forEach(w=>assert.ok(a.words.includes(w)));assert.equal(a.words.length,43127);for(const w of ['ZEBRA','QUARTZ','ELEPHANT','COMPUTER','BANANA'])assert.ok(a.words.includes(w));for(const w of ['CTA','CA','ABCDEFGHI','<SCRIPT>'])assert.ok(!a.words.includes(w));});
check('C1 saved schema restores board, pending tiles and inventory unchanged',()=>{let s=state();cat(s);a.place(s,49,3);const raw=JSON.stringify(s);assert.equal(s.wordlist,1);assert.equal(JSON.stringify(a.parseState(raw)),raw);});
check('new dictionary word is accepted and scored with the same rules',()=>{let s=state();s.rack=['Z','E','B','R','A','S','O'];[38,39,40,41,42].forEach((i,r)=>a.place(s,i,r));assert.ok(a.submit(s).ok);assert.equal(s.score,5);});
check('independent 9x9 boards, seven-letter racks and conserved bag',()=>{let x=state(),y=state();assert.equal(x.board.length,81);assert.equal(x.rack.join(''),'CATRESO');assert.equal(inventory(x),[...a.bag].sort().join(''));x.board[1]='Z';x.rack[0]='B';x.pool.length=0;assert.equal(y.board[1],'');assert.equal(y.rack[0],'C');assert.ok(y.pool.length);});
check('ready and finished states reject placement, exchange and submit',()=>{for(const status of ['ready','gameover']){let s=state();s.status=status;const before=JSON.stringify(s);assert.equal(a.place(s,40,0),false);assert.equal(a.exchange(s),false);assert.equal(a.submit(s).ok,false);assert.equal(JSON.stringify(s),before);}});
check('invalid cell/rack coordinates and duplicate inventory use are rejected',()=>{let s=state();for(const i of [-1,81,NaN,1.2,'40'])assert.equal(a.place(s,i,0),false);for(const r of [-1,7,null,1.5])assert.equal(a.place(s,40,r),false);assert.ok(a.place(s,40,0));assert.equal(a.place(s,41,0),false);assert.equal(a.place(s,40,1),false);});
check('uncommitted tile can be removed and reused',()=>{let s=state();a.place(s,40,0);assert.ok(a.remove(s,40));assert.ok(a.place(s,41,0));assert.equal(s.score,0);assert.equal(s.board[40],'');assert.equal(s.rack[0],'C');});
check('first move must cross center and contain at least two letters',()=>{let s=state();a.place(s,0,0);a.place(s,1,1);a.place(s,2,2);assert.equal(a.submit(s).ok,false);s.pending=[];a.place(s,40,1);assert.equal(a.submit(s).ok,false);});
check('CAT commits, scores three, refills rack and preserves inventory',()=>{let s=state(),before=inventory(s),result=cat(s);assert.ok(result.ok);assert.equal(result.points,3);assert.equal(s.board.slice(39,42).join(''),'CAT');assert.equal(s.score,3);assert.equal(s.turns,1);assert.equal(s.pending.length,0);assert.equal(inventory(s),before);assert.equal(s.rack.filter(Boolean).length,7);assert.ok(a.parseState(JSON.stringify(s)));});
check('vertical first move is accepted',()=>{let s=state();a.place(s,31,0);a.place(s,40,1);a.place(s,49,2);assert.ok(a.submit(s).ok);assert.equal(s.score,3);});
check('diagonal, gapped and row-wrapped moves are rejected',()=>{for(const positions of [[30,40,50],[38,40,41],[35,36,40]]){let s=state();positions.forEach((index,r)=>a.place(s,index,r));assert.equal(a.submit(s).ok,false);}});
check('dictionary rejection is atomic and leaves pending correction available',()=>{let s=state();a.place(s,39,0);a.place(s,40,2);a.place(s,41,1);const before=JSON.stringify(s);const result=a.submit(s);assert.equal(result.ok,false);assert.ok(result.message.includes('CTA'));assert.equal(JSON.stringify(s),before);});
check('placement cannot overwrite a committed tile',()=>{let s=state();cat(s);assert.equal(a.place(s,40,3),false);});
check('later words must connect to the existing board',()=>{let s=state();cat(s);s.rack=['C','A','R','E','S','O','T'];a.place(s,0,0);a.place(s,1,1);a.place(s,2,2);assert.equal(a.submit(s).ok,false);});
check('single tile forms and scores connected word',()=>{let s=state();cat(s);s.rack[3]='T';a.place(s,49,3);const result=a.submit(s);assert.ok(result.ok);assert.equal(result.words[0].word,'AT');assert.equal(s.score,5);});
check('existing letter may bridge newly placed tiles',()=>{let s=state();cat(s);s.rack[3]='C';s.rack[4]='R';a.place(s,31,3);a.place(s,49,4);const result=a.submit(s);assert.ok(result.ok);assert.equal(result.words[0].word,'CAR');});
check('all crossing words are validated, not only the main word',()=>{let s=state();cat(s);s.rack[3]='A';s.rack[4]='T';a.place(s,48,3);a.place(s,49,4);const result=a.submit(s);assert.equal(result.ok,false);assert.ok(result.message.includes('CA'));});
check('one tile can score two crossing words without duplication',()=>{let s=state();s.board[39]='C';s.board[41]='T';s.board[31]='C';s.board[49]='R';a.place(s,40,1);const result=a.submit(s);assert.ok(result.ok);assert.equal(result.points,6);assert.equal(new Set(result.words.map(w=>w.word)).size,2);});
check('exchange conserves inventory and does not score',()=>{let s=state(),before=inventory(s);assert.ok(a.exchange(s,()=>.1));assert.equal(inventory(s),before);assert.equal(s.score,0);assert.equal(s.turns,1);a.place(s,40,0);assert.equal(a.exchange(s),false);s.pending=[];s.pool=[];assert.equal(a.exchange(s),false);});
check('pending placements round-trip through bounded saved schema',()=>{let s=state();a.place(s,40,0);const copy=a.parseState(JSON.stringify(s));assert.ok(copy);assert.equal(JSON.stringify(copy),JSON.stringify(s));copy.pending[0].index=41;assert.equal(s.pending[0].index,40);});
check('corrupt, oversized, future-version and script-like saved data are rejected',()=>{for(const raw of [null,'{','[]','x'.repeat(20000)])assert.equal(a.parseState(raw),null);for(const change of [s=>s.schema=2,s=>s.wordlist=2,s=>s.status='evil',s=>s.score=-1,s=>s.score=10001,s=>s.turns=1.5,s=>s.board[0]='<script>',s=>s.rack[0]='aa',s=>s.pool.push('Q'),s=>s.board.pop(),s=>s.rack.pop()]){let s=state();change(s);assert.equal(a.parseState(JSON.stringify(s)),null);}});
check('saved duplicate and overlapping pending placements are rejected',()=>{for(const pending of [[{index:40,rackIndex:0},{index:40,rackIndex:1}],[{index:40,rackIndex:0},{index:41,rackIndex:0}],[{index:81,rackIndex:0}],[{index:40,rackIndex:7}]]){let s=state();s.pending=pending;assert.equal(a.parseState(JSON.stringify(s)),null);}});
check('100 seeded action sequences conserve every letter and saved-state invariants',()=>{for(let seed=1;seed<=100;seed++){let s=state(),initial=inventory(s),n=seed;function rng(){n=(n*1664525+1013904223)>>>0;return n/4294967296;}cat(s);for(let i=0;i<200;i++){if(rng()<.3){s.pending=[];a.exchange(s,rng);}else{a.place(s,Math.floor(rng()*81),Math.floor(rng()*7));if(rng()<.3)a.submit(s);if(rng()<.3)s.pending=[];}assert.equal(inventory(s),initial);assert.ok(a.parseState(JSON.stringify(s)));assert.ok(s.score>=0);}}});
console.log('RESULT: PASS '+count+' / FAIL 0 / SKIP 0');
