from pathlib import Path
import re

from dashboard_source_utils import dashboard_source
ROOT = Path(__file__).resolve().parents[1]
checks: list[bool] = []

def check(condition: bool, message: str) -> None:
    checks.append(bool(condition))
    print(('PASS' if condition else 'FAIL') + ': ' + message)

version = (ROOT / 'app/version.php').read_text(encoding='utf-8')
bootstrap = (ROOT / 'app/bootstrap.php').read_text(encoding='utf-8')
widget = (ROOT / 'app/dashboard_widget.php').read_text(encoding='utf-8')
game = (ROOT / 'app/mini_game.php').read_text(encoding='utf-8')
api = (ROOT / 'app/api.php').read_text(encoding='utf-8')
index = dashboard_source(ROOT)
dashboard_js = (ROOT / 'public/js/dashboard.js').read_text(encoding='utf-8')
game_js = (ROOT / 'public/js/mini-game.js').read_text(encoding='utf-8')
game_css = (ROOT / 'public/css/mini-game.css').read_text(encoding='utf-8')
schema = (ROOT / 'database/schema.sql').read_text(encoding='utf-8')
migrations = list((ROOT / 'database/migrations').glob('*'))
run = (ROOT / 'tests/run.sh').read_text(encoding='utf-8')

version_match = re.search(r"const APP_VERSION = '(\d+)\.(\d+)\.(\d+)(?:-dev\.[1-9][0-9]*)?';", version)
version_tuple = tuple(int(part) for part in version_match.groups()) if version_match else (0, 0, 0)
label_match = re.search(r"const APP_VERSION_LABEL = 'RSS Reader Modernization (?:V)?(\d+)\.(\d+)(?:\.(\d+)|-[^']*)';", version)
label_tuple = (
    (int(label_match.group(1)), int(label_match.group(2)), int(label_match.group(3) or 0))
    if label_match else (0, 0, 0)
)
check(version_tuple >= (1, 4, 0), 'Application retains Version 1.4 Game support in V1.4 or later')
check(label_tuple >= (1, 4, 0), 'visible label identifies Version 1.4 or later work')
check("require_once __DIR__ . '/mini_game.php';" in bootstrap, 'Bootstrap loads Mini Game domain code')
check("'game'" in re.search(r'function dashboard_widget_types\(\): array\s*\{(.*?)\}', widget, re.S).group(1), 'Game is an allowed Dashboard Widget type')
check("'game' => mini_game_widget_config_from_storage" in widget, 'Game config is normalized with the Widget row')
check('mini_game_widget_defaults' in game and 'mini_game_widget_config_from_input' in game, 'Game config has explicit defaults and input validation')
check("'icon_quest'" in game and "'lights_out'" in game, 'approved Game types retain Icon Quest and include Lights Out')
check('mini_game_widget_create' in game and 'mini_game_widget_update' in game and 'mini_game_widget_delete' in game, 'Game Widget owner-scoped CRUD is implemented')
check("'game', NULL" in game and 'dashboard_widget' in game, 'Game uses existing dashboard_widget table with a null reference')
check('dashboard_widget_next_sort_order' in game and 'dashboard_widget_lock_owned_widget' in game, 'Game reuses existing order and owner lock helpers')
check('beginTransaction' in game and 'rollBack' in game and 'commit' in game, 'Game Widget mutations are transactional')
check("'widget.game.create' => api_widget_game_create" in api and "'widget.game.update' => api_widget_game_update" in api and "'widget.game.delete' => api_widget_game_delete" in api, 'Game CRUD actions are registered')
check('mini_game_widget_create($userId' in api and 'mini_game_widget_update($userId' in api and 'mini_game_widget_delete($userId' in api, 'Game owner comes only from authenticated Session')
check("$input['widget_owner']" not in api, 'Game API does not trust a client owner field')
check('data-dashboard-widget-type="game"' in index and 'data-dashboard-swipe-ignore="true"' in index, 'Game renders as a Widget and opts out of Tab swipe')
check('data-dashboard-user-id' in index, 'authenticated User ID is available only as a Storage namespace')
check('fa-user-shield' in index and 'fa-skull-crossbones' in index and 'fa-gem' in index and 'fa-door-open' in index, 'Game board uses bundled Font Awesome icons')
check('role="grid"' in index and 'role="gridcell"' in index and 'aria-rowindex' in index and 'aria-colindex' in index, 'Game board has grid accessibility semantics')
check('id="registerGameWidgetForm"' in index and 'id="changeGameWidgetForm"' in index, 'Game add and edit forms are explicit')
check('Game追加' in index and 'data-target="#registerGameWidget"' in index, 'Drawer exposes Game Widget addition')
check('mini-game.css' in index and 'mini-game.js' in index, 'Mini Game assets are loaded separately')
check("apiRequest('widget.game.create'" in dashboard_js and "apiRequest('widget.game.update'" in dashboard_js and "apiRequest('widget.game.delete'" in dashboard_js, 'Frontend mutations use protected API actions')
check('window.RssMiniGame.removeWidgetState(widgetId)' in dashboard_js, 'successful Widget deletion removes its Browser state')
check("rssReader.miniGame.iconQuest.v1" in game_js and ".user.' + safeUserId + '.widget.' + safeWidgetId" in game_js, 'Storage key separates version, User and Widget')
check("browserStorage('localStorage')" in game_js and "browserStorage('sessionStorage')" in game_js and "storageMode = 'memory'" in game_js, 'Storage wrapper has local, session and memory modes')
check('JSON.parse' in game_js and 'validateState' in game_js and 'JSON.stringify' in game_js, 'Storage data is parsed and validated before use')
check('innerHTML' not in game_js, 'Storage values are never written through innerHTML')
check('querySelectorAll(\'[data-dashboard-widget-type="game"]\')' in game_js, 'all Game Widgets initialize independently')
check('.mini-game-card-header' in game_css and 'height: 44px' in game_css, 'Game header matches the existing 44px Widget header')
check('min-width: 44px' in game_css and 'min-height: 44px' in game_css, 'Game cells meet the 44px interaction target')
check('@media (prefers-reduced-motion: reduce)' in game_css, 'Game styling supports reduced motion')
check('grid-template-columns: repeat(5' in game_css, 'Game board is a fixed 5-column grid')
check('CREATE TABLE' in schema and 'dashboard_widget' in schema, 'existing schema still contains the generic Widget table')
check(not any('v14' in path.name.lower() for path in migrations), 'V1.4-B adds no migration')
check('test_v14b_game_widget.php' in run and 'test_v14b_storage_runtime.js' in run, 'main test runner includes V1.4-B checks')

if not all(checks):
    raise SystemExit(f'{checks.count(False)}/{len(checks)} V1.4-B architecture checks failed')
print(f'All {len(checks)} V1.4-B architecture checks passed.')
