from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
checks: list[bool] = []

def check(condition: bool, message: str) -> None:
    checks.append(bool(condition))
    print(('PASS' if condition else 'FAIL') + ': ' + message)

widget = (ROOT / 'app/dashboard_widget.php').read_text(encoding='utf-8')
api = (ROOT / 'app/api.php').read_text(encoding='utf-8')
index = (ROOT / 'public/index.php').read_text(encoding='utf-8')
js = (ROOT / 'public/js/dashboard.js').read_text(encoding='utf-8')
css = (ROOT / 'public/css/dashboard.css').read_text(encoding='utf-8')
version = (ROOT / 'app/version.php').read_text(encoding='utf-8')
run = (ROOT / 'tests/run.sh').read_text(encoding='utf-8')
postflight = (ROOT / 'database/audit/v1_1_d_postflight.sql').read_text(encoding='utf-8')
local_run = (ROOT / 'tests/run-local-v1-1-e.sh').read_text(encoding='utf-8')

check("'widget.reorder' => api_widget_reorder" in api, 'Widget reorder API action is registered')
check('dashboard_widget_decode_order_list' in widget and 'array_is_list' in widget and 'array_unique' in widget, 'order payload is a bounded unique list')
check('dashboard_widget_lock_order' in widget and 'FOR UPDATE' in widget, 'current order is locked before update')
check("widget_owner = :owner" in widget and "widget_location = :location" in widget, 'reorder SQL is owner and tab scoped')
check('currentIds !== $previousIds' in widget and "'conflict' => true" in widget, 'stale browser order is detected')
check("widget_sort_order = :sort_order" in widget and "($index + 1) * 10" in widget, 'saved order uses stable increments')
check('beginTransaction' in widget and 'rollBack' in widget and 'commit' in widget, 'reorder remains transactional')
check("dashboard_widget_next_sort_order" in widget and 'ORDER BY widget_sort_order DESC' in widget, 'new Feed appends after the current order')
check("$input['widget_owner']" not in api and 'dashboard_widget_reorder($userId' in api, 'authenticated owner is the only reorder owner source')
check("widget_order_conflict" in api and '409' in api, 'stale reorder has a structured conflict response')

check('class="btn btn-link widget-drag-handle"' in index and 'draggable="false"' in index and 'fa-grip-lines' in index and 'widget-drag-label' not in index and '>移動</span>' not in index, 'title bar shows only the Drag icon without a visible text label')
check('aria-describedby="widget-sort-help"' in index and '矢印キー' in index, 'Keyboard instructions are connected to the handle')
check('data-dashboard-widget-location' in index and 'aria-busy="false"' in index, 'Feed grid exposes save scope and busy state')
check("apiRequest('widget.reorder'" in js, 'Frontend saves order through the Secure Baseline API helper')
check("'previous_widget_ids': JSON.stringify(previousIds)" in js, 'Frontend sends its previous order for conflict detection')
check("'widget_ids': JSON.stringify(orderedIds)" in js, 'Frontend sends the new order explicitly')
check(".off('dragstart' + eventNamespace" not in js and "original.pointerType === 'mouse' && original.button !== 0" in js, 'Mouse uses the same Pointer path as Touch and Pen')
check("pointerdown" in js and "pointermove" in js and "pointercancel" in js and "setPointerCapture" in js, 'Mouse, Touch and Pen pointer paths are handled')
check('widgetCreateDragGhost' in js and 'widgetPositionGhost' in js and 'widgetRemoveDragGhost' in js, 'Drag uses a lightweight pointer-following preview')
check('widgetApplyDrop' in js and 'dropTarget' in js and 'dropBefore' in js, 'DOM order changes only once when the pointer is released')
check("['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End']" in js, 'Keyboard reorder offers arrows, Home and End')
check('widgetRestoreOrder' in js and "requestFail(xhr, textStatus)" in js, 'failed save restores the visual order')
check("showNotice('Widgetの並び順を保存しました', 'success', 2500)" in js and 'noticeTimer' in js, 'reorder completion notice closes automatically')
check("attr('draggable', 'false')" in js, 'Feed links are not mistaken for Drag sources')
check('touch-action: none' in css and '.widget-drag-handle' in css, 'only the reorder handle captures Touch movement')
check('width: 28px' in css and 'height: 32px' in css and 'border: 1px solid' in css and 'max-width: calc(100% - 82px)' in css, 'compact icon-only Drag button leaves more title width')
check("addClass('text-white feed-title-text')" in js and "addClass('fas fa-bell')" in js and "addClass('feed-new-count')" in js, 'Feed heading uses a Bell and count instead of the large NEW badge')
check(".text('NEW ' + newCount)" not in js and "badge badge-warning feed-new-clear" not in js, 'large Feed heading NEW badge is removed')
check("badge badge-warning feed-item-new" not in js and ".text('NEW')" not in js and js.count("addClass('fas fa-bell')") >= 2, 'article NEW label is replaced by a compact Bell-only control')
check('height: 44px' in css and '.feed-title-text' in css and 'text-overflow: ellipsis' in css and 'white-space: nowrap' in css, 'Feed headings keep one compact and even title row')
check('.feed-new-clear {' in css and 'background: transparent' in css and 'font-size: 11px' in css, 'Bell count stays visually quiet without a badge background')
check('.widget-drag-handle .svg-inline--fa' in css and 'pointer-events: none' in css, 'the icon cannot narrow the Drag button target')
check('.widget-dragging' in css and '.widget-drag-ghost' in css and '.widget-drop-horizontal' in css and '.widget-drop-vertical' in css, 'Drag state follows the pointer and shows an insertion line')
check(("const APP_VERSION = '1.1.0-dev." in version and 'RSS Reader Modernization V1.1-' in version) or ("const APP_VERSION = '1.1.0';" in version and 'RSS Reader Modernization 1.1.0' in version) or "const APP_VERSION = '1.2.0-dev.1';" in version, 'visible Version marker remains V1.1-E or later')
check(not any('reorder' in p.read_text(encoding='utf-8').lower() for p in (ROOT / 'database/migrations').glob('004_*.sql')), 'V1.1-E reorder remains independent from later Memo migration')
check("@database_name = DATABASE()" in postflight and "@database_is_application" in postflight, 'V1.1-D R2 postflight validates the selected database')
check("NOT IN ('information_schema', 'mysql', 'performance_schema', 'sys')" in postflight, 'postflight refuses system database selection')
check("'`.`'" in postflight and 'missing_feed_widgets' in postflight, 'postflight fully qualifies application table names')
check('test_v11e_widget_reorder.php' in run and 'test_v11e_frontend_runtime.js' in run, 'main regression runner includes V1.1-E checks')
check('test_v11e_widget_reorder.php' in local_run and 'test_v11e_frontend_runtime.js' in local_run, 'local V1.1 runner includes V1.1-E checks')

if not all(checks):
    raise SystemExit(f'{checks.count(False)}/{len(checks)} V1.1-E architecture checks failed')
print(f'All {len(checks)} V1.1-E architecture checks passed.')
