'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');
const root=path.resolve(__dirname,'..');let checks=0;
function check(condition,name){assert.ok(condition,name);checks++;console.log('PASS: '+name);}
function card(id,type='maze_chase'){return `<section class="mini-game-card dashboard-widget" data-dashboard-widget-id="${id}" data-dashboard-widget-type="game" data-mini-game-type="${type}" data-dashboard-swipe-ignore="true"><div class="mini-game-card-inner"><div class="mini-game-card-header"><button class="widget-drag-handle">並替</button><span class="mini-game-title">${type}</span><button class="mini-game-edit-trigger">編集</button></div><div class="mini-game-card-body"><p>Loading</p></div></div></section>`;}
function html(cards){return `<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="/css/bootstrap-5.3.8.min.css"><link rel="stylesheet" href="/css/mini-game.css"><link rel="stylesheet" href="/css/game-widget.css"><link rel="stylesheet" href="/css/game-2048.css"><link rel="stylesheet" href="/css/reversi.css"></head><body><button id="outside">外側</button><select class="registerGameType" id="registerGameType"><option value="icon_quest">Icon</option><option value="maze_chase">Maze</option><option value="game_2048">2048</option></select><input class="registerGameTitleValue" value="Icon Quest"><div id="main-content" data-dashboard-user-id="7">${cards}</div><div style="height:1800px"></div><script src="/js/jquery-3.7.1.min.js"></script><script src="/js/game-widget.js?v=fixture-revision"></script><script src="/js/mini-game.js"></script><script src="/js/lights-out.js"></script><script src="/js/cursor-field.js"></script><script src="/js/game-2048.js"></script><script src="/js/reversi.js"></script><script src="/js/block-collapse.js"></script></body></html>`;}
(async()=>{
const browser=await chromium.launch({executablePath:process.env.GAME_TEST_CHROME||chromium.executablePath(),headless:true,args:['--no-sandbox']});
async function setup(viewport,cards,options={}){
 const context=await browser.newContext({viewport,hasTouch:viewport.width<600}); const requests=[],errors=[];let failures=options.failOnce?1:0;
 await context.addInitScript(()=>{window.__frames=0;const raf=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=function(fn){return raf(t=>{window.__frames++;fn(t);});};if(location.search.includes('blocked')){for(const name of ['localStorage','sessionStorage'])Object.defineProperty(window,name,{get(){throw new Error('blocked');}});}});
 await context.route('http://game.test/**',async route=>{let url=new URL(route.request().url());requests.push(url.pathname+url.search);if(url.pathname==='/'){await route.fulfill({contentType:'text/html',body:html(cards)});return;}if(url.pathname==='/js/maze-chase.js'&&failures-- >0){await route.abort();return;}const file=path.join(root,'public',url.pathname);if(fs.existsSync(file))await route.fulfill({body:fs.readFileSync(file),contentType:url.pathname.endsWith('.js')?'text/javascript':'text/css'});else await route.fulfill({status:404,body:''});});
 const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto('http://game.test/'+(options.blocked?'?blocked=1':''));return {page,context,requests,errors};
}
let e=await setup({width:1280,height:1000},'');await e.page.waitForTimeout(200);check(!e.requests.some(x=>x.includes('maze-chase.js')),'unconfigured Dashboard never requests Maze module');check(e.errors.length===0,'legacy scripts work without Game cards');await e.context.close();
for(const viewport of [{width:1280,height:1000},{width:360,height:1000}]){
 e=await setup(viewport,card(1)+card(2));const p=e.page;await p.waitForSelector('[data-game-widget-initialized="1"]');await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===2);
 check(e.requests.filter(x=>x.includes('maze-chase.js')).length===1,'multiple widgets share one module request at '+viewport.width);
 check(e.requests.includes('/js/maze-chase.js?v=fixture-revision'),'child module inherits revision');
 const first=p.locator('.mini-game-card').nth(0),second=p.locator('.mini-game-card').nth(1);
 check(await first.locator('.maze-chase-board').count()===1 && await first.locator('.mini-game-board').count()===0,'legacy Icon engine does not initialize Maze');
 await p.selectOption('#registerGameType','maze_chase');check(await p.inputValue('.registerGameTitleValue')==='Maze Chase','Maze default title survives legacy listeners');await p.fill('.registerGameTitleValue','自分の題名');await p.selectOption('#registerGameType','game_2048');check(await p.inputValue('.registerGameTitleValue')==='自分の題名','custom title is retained');
 await first.locator('.game-widget-start').click();await first.locator('.maze-chase-board').press('ArrowRight');await p.waitForFunction(()=>Number(document.querySelector('.game-widget-score').textContent)>0);
 check(await second.locator('.game-widget-score').textContent()==='0','starting and scoring one Widget does not affect another');
 check(await p.evaluate(()=>{const board=document.querySelector('.maze-chase-board');return !board.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));}),'board consumes movement key');
 check(await p.evaluate(()=>document.getElementById('outside').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}))),'outside key keeps normal page behavior');
 await first.locator('.game-widget-pause').click();let frames=await p.evaluate(()=>window.__frames),score=await first.locator('.game-widget-score').textContent();await p.waitForTimeout(350);check(await p.evaluate(()=>window.__frames)===frames,'Pause stops animation callbacks');
 await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});check(await first.locator('.game-widget-pause').textContent()==='Resume','visibility return preserves user Pause');
 await first.locator('.game-widget-expand').click();check(await p.evaluate(()=>document.body.style.overflow)==='hidden','expansion locks page scroll');await first.locator('.game-widget-expand').press('Escape');check(await p.evaluate(()=>document.body.style.overflow)!=='hidden','Escape exits expansion and restores scrolling');
 await first.locator('.game-widget-start').click();check(await first.locator('.game-widget-score').textContent()==='0','Restart resets score');check(Number(await first.locator('.game-widget-best').textContent())>=Number(score),'Restart retains Best');
 await first.locator('[data-game-direction="right"]').click();await p.waitForFunction(()=>Number(document.querySelector('.game-widget-score').textContent)>0);check(true,'direction button moves on '+viewport.width);
 let rect=await first.locator('.maze-chase-board').boundingBox();check(rect.width<=viewport.width,'board fits viewport');
 await first.locator('.game-widget-expand').click();await p.evaluate(()=>document.querySelector('.mini-game-card').remove());await p.waitForTimeout(150);check(await p.evaluate(()=>document.body.style.overflow)!=='hidden','removing expanded Widget restores page scroll');frames=await p.evaluate(()=>window.__frames);await p.waitForTimeout(200);check(await p.evaluate(()=>window.__frames)===frames,'removing running Widget stops its loop');
 await p.evaluate(markup=>document.getElementById('main-content').insertAdjacentHTML('afterbegin',markup),card(1));await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===2);check(Number(await p.locator('.mini-game-card').first().locator('.game-widget-best').textContent())>0,'replacement restores scoped Best');
 await p.reload();await p.waitForFunction(()=>document.querySelectorAll('[data-game-widget-initialized="1"]').length===2);check(Number(await p.locator('.mini-game-card').first().locator('.game-widget-best').textContent())>0,'reload persists Best');
 check(e.errors.length===0,'no browser exceptions at '+viewport.width);await e.context.close();
}
e=await setup({width:800,height:900},card(1),{failOnce:true});await e.page.getByRole('button',{name:'再試行',exact:true}).click();await e.page.waitForSelector('[data-game-widget-initialized="1"]');check(e.requests.filter(x=>x.includes('maze-chase.js')).length===2,'failed lazy load can retry');await e.context.close();
e=await setup({width:800,height:900},card(1),{blocked:true});await e.page.waitForSelector('[data-game-widget-initialized="1"]');check((await e.page.locator('.game-widget-storage-note').textContent()).includes('画面内'),'blocked Storage falls back to memory without failure');await e.context.close();
e=await setup({width:1280,height:1400},card(1,'reversi')+card(2,'game_2048')+card(3,'wire_defense')+card(4,'block_collapse')+card(5,'cursor_field'));
await e.page.waitForSelector('.reversi-cell');check(await e.page.locator('.reversi-cell').count()===64,'Reversi still initializes 64 cells');check(await e.page.locator('.game-2048-cell').count()===16,'2048 still initializes 16 cells');check(await e.page.locator('.wire-defense-canvas').count()===1,'Wire Defense still initializes');check(await e.page.locator('.block-collapse-canvas').count()===1,'Block Collapse still initializes');check(await e.page.locator('.cursor-field-canvas').count()===1,'Cursor Field still initializes');check(!e.requests.some(x=>x.includes('maze-chase.js')),'legacy Games do not request Maze');check(e.errors.length===0,'legacy family reports no browser exceptions');await e.context.close();
await browser.close();console.log('RESULT: PASS '+checks+' / FAIL 0 / SKIP 0');
})().catch(error=>{console.error(error);process.exit(1);});
