from pathlib import Path
import shutil,sys
ROOT=Path(__file__).resolve().parents[1];CSS=ROOT/'public/css/mini-game.css';JS=ROOT/'public/js/mini-game.js';checks=[]
def check(ok,msg): checks.append(bool(ok)); print(('PASS' if ok else 'FAIL')+': '+msg)
try: from playwright.sync_api import sync_playwright
except Exception: print('SKIP: Playwright unavailable.'); raise SystemExit(0)
chromium=shutil.which('chromium') or shutil.which('google-chrome')
if not chromium: print('SKIP: Chromium unavailable.'); raise SystemExit(0)
def card(w):
 cells=''.join(f'<button class="mini-game-cell" data-mini-game-cell-index="{i}" tabindex="{0 if i==0 else -1}" aria-label="cell {i}"></button>' for i in range(25))
 return f'''<section class="mini-game-card" data-dashboard-widget-id="{w}" data-dashboard-widget-type="game"><div class="mini-game-card-body"><div class="mini-game-summary"><b class="mini-game-level"></b><b class="mini-game-moves"></b><b class="mini-game-best"></b><b class="mini-game-treasure-state"></b><b class="mini-game-enemy-turn"></b></div><div class="mini-game-board">{cells}</div><p class="mini-game-status"></p><div class="mini-game-controls"><div class="mini-game-action-buttons"><button class="mini-game-new-game">New</button><button class="mini-game-reset">Reset</button></div><div class="mini-game-dpad"><button class="mini-game-direction mini-game-direction-up" data-mini-game-direction="up">U</button><button class="mini-game-direction mini-game-direction-left" data-mini-game-direction="left">L</button><button class="mini-game-direction mini-game-direction-down" data-mini-game-direction="down">D</button><button class="mini-game-direction mini-game-direction-right" data-mini-game-direction="right">R</button></div></div><p class="mini-game-storage-note"></p></div></section>'''
html=f'<main id="main-content" data-dashboard-user-id="77">{card(101)}{card(102)}</main>'
storage="""() => {const v={};const s={getItem:k=>v[k]||null,setItem:(k,x)=>v[k]=String(x),removeItem:k=>delete v[k]};Object.defineProperty(window,'localStorage',{value:s,configurable:true});Object.defineProperty(window,'sessionStorage',{value:s,configurable:true});window.__v=v;}"""
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=chromium,headless=True,args=['--no-sandbox']);page=b.new_page(viewport={'width':360,'height':1000});page.on('dialog',lambda d:d.accept());page.set_content(html);page.add_style_tag(path=str(CSS));page.evaluate(storage);page.add_script_tag(path=str(JS));page.wait_for_function("document.querySelectorAll('[data-mini-game-initialized=\"1\"]').length===2");first=page.locator('.mini-game-card').first
 check(page.evaluate('document.documentElement.scrollWidth<=document.documentElement.clientWidth'),'360px has no horizontal overflow');box=first.locator('.mini-game-cell').first.bounding_box();check(box and box['height']>=44,'cell has 44px target');first.locator('[data-mini-game-cell-index="1"]').click();check(first.locator('.mini-game-moves').inner_text()=='1 / 20','adjacent Tap moves Player');first.locator('[data-mini-game-cell-index="1"]').press('ArrowDown');check(first.locator('.mini-game-moves').inner_text()=='2 / 20','Arrow Key moves Player');first.locator('.mini-game-reset').click();check(first.locator('.mini-game-moves').inner_text()=='0 / 20','Reset works');sel={'R':'.mini-game-direction-right','D':'.mini-game-direction-down'}
 for ch in 'RDDRRDRD': first.locator(sel[ch]).click()
 check(first.get_attribute('data-mini-game-status')=='won','Level 1 clears through UI');check(first.locator('.mini-game-best').inner_text()=='8','Best displays');check(page.locator('.mini-game-card').nth(1).locator('.mini-game-moves').inner_text()=='0 / 20','multiple Widgets are isolated');page.evaluate("markup=>{document.getElementById('main-content').innerHTML=markup;RssMiniGame.init()}",card(101)+card(102));check(page.locator('.mini-game-card').first.get_attribute('data-mini-game-status')=='won','state restores after Dashboard rerender');page.locator('.mini-game-card').first.locator('.mini-game-new-game').click();check(page.locator('.mini-game-card').first.locator('.mini-game-level').inner_text()=='Level 2','New Game advances Level');b.close()
failed=len(checks)-sum(checks);print(f'RESULT: PASS {sum(checks)} / FAIL {failed} / SKIP 0');sys.exit(1 if failed else 0)
