<?php

declare(strict_types=1);

/**
 * SB-13 schema / data-integrity metadata and audit helpers.
 *
 * This file deliberately contains no destructive cleanup. Duplicate identities,
 * orphan rows, and legacy credential formats are report-only gates.
 */

const SB13_SCHEMA_VERSION = 'SB-13 R2';
const SB13_TARGET_CHARSET = 'utf8mb4';
const SB13_TARGET_COLLATION = 'utf8mb4_unicode_ci';

/** @return list<string> */
function sb13_tables(): array
{
    return [
        db_table_name('user_info'),
        db_table_name('user_conf'),
        db_table_name('content'),
        db_table_name('content_stock'),
    ];
}

/**
 * Indexes required by the Secure Baseline after SB-13.
 * Prefix length is represented as `column(64)`.
 *
 * @return array<string, array<string, array{unique: bool, columns: list<string>}>>
 */
function sb13_required_indexes(): array
{
    return [
        db_table_name('user_info') => [
            'PRIMARY' => ['unique' => true, 'columns' => ['user_id']],
            'idx_user_identity_flag_id' => [
                'unique' => false,
                'columns' => ['user_email(64)', 'user_flag', 'user_id'],
            ],
        ],
        db_table_name('user_conf') => [
            'PRIMARY' => ['unique' => true, 'columns' => ['conf_id']],
            'uq_user_conf_user_id' => ['unique' => true, 'columns' => ['user_id']],
        ],
        db_table_name('content') => [
            'PRIMARY' => ['unique' => true, 'columns' => ['content_id']],
            'idx_content_owner_location_flag_id' => [
                'unique' => false,
                'columns' => ['content_owner', 'content_location', 'content_flag', 'content_id'],
            ],
        ],
        db_table_name('content_stock') => [
            'PRIMARY' => ['unique' => true, 'columns' => ['stock_id']],
            'idx_stock_owner_flag_id' => [
                'unique' => false,
                'columns' => ['stock_owner', 'stock_flag', 'stock_id'],
            ],
        ],
    ];
}

/**
 * Columns that are IDs referencing an unsigned user_id and are normalized to
 * UNSIGNED by the SB-13 migration. This does not create foreign keys.
 *
 * @return array<string, list<string>>
 */
function sb13_unsigned_relationship_columns(): array
{
    return [
        db_table_name('user_conf') => ['user_id'],
        db_table_name('content') => ['content_owner'],
        db_table_name('content_stock') => ['stock_owner'],
    ];
}

/**
 * Classify an audit snapshot. The function is pure so negative / gate behavior
 * can be tested without a database driver.
 *
 * Required snapshot keys are generated by sb13_collect_audit().
 *
 * @param array<string, mixed> $snapshot
 * @return array{blocking: list<string>, warnings: list<string>}
 */
function sb13_classify_audit(array $snapshot): array
{
    $blocking = [];
    $warnings = [];

    $userInfo = db_table_name('user_info');
    $userConf = db_table_name('user_conf');
    $content = db_table_name('content');
    $contentStock = db_table_name('content_stock');

    $requiredTables = sb13_tables();
    $presentTables = array_values(array_filter(
        $snapshot['present_tables'] ?? [],
        static fn (mixed $value): bool => is_string($value)
    ));

    foreach ($requiredTables as $table) {
        if (!in_array($table, $presentTables, true)) {
            $blocking[] = "Required table is missing: {$table}";
        }
    }

    $duplicateConf = (int) ($snapshot['duplicate_user_conf_user_ids'] ?? 0);
    if ($duplicateConf > 0) {
        $blocking[] = "{$userConf} has {$duplicateConf} duplicated user_id group(s); unique 1:1 constraint cannot be applied.";
    }

    $negativeRelationshipIds = (int) ($snapshot['negative_relationship_ids'] ?? 0);
    if ($negativeRelationshipIds > 0) {
        $blocking[] = "Relationship columns contain {$negativeRelationshipIds} negative value(s); UNSIGNED conversion would be unsafe.";
    }

    $duplicateIdentity = (int) ($snapshot['duplicate_identity_groups'] ?? 0);
    if ($duplicateIdentity > 0) {
        $warnings[] = "{$userInfo} contains {$duplicateIdentity} duplicate identity group(s); they are preserved and no UNIQUE identity constraint is added.";
    }

    $orphanContent = (int) ($snapshot['orphan_content_rows'] ?? 0);
    if ($orphanContent > 0) {
        $warnings[] = "{$content} contains {$orphanContent} orphan owner row(s); they are preserved and no foreign key is added.";
    }

    $orphanStock = (int) ($snapshot['orphan_stock_rows'] ?? 0);
    if ($orphanStock > 0) {
        $warnings[] = "{$contentStock} contains {$orphanStock} orphan owner row(s); they are preserved and no foreign key is added.";
    }

    $orphanConf = (int) ($snapshot['orphan_conf_rows'] ?? 0);
    if ($orphanConf > 0) {
        $warnings[] = "{$userConf} contains {$orphanConf} orphan row(s); they are preserved.";
    }

    $missingConf = (int) ($snapshot['users_missing_conf'] ?? 0);
    if ($missingConf > 0) {
        $warnings[] = "{$missingConf} user(s) have no {$userConf} row; migration does not synthesize missing settings.";
    }

    return ['blocking' => $blocking, 'warnings' => $warnings];
}

/**
 * Collect a read-only integrity snapshot from the current database.
 *
 * @return array<string, mixed>
 */
function sb13_collect_audit(PDO $pdo): array
{
    $driver = (string) $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
    if ($driver !== 'mysql') {
        throw new RuntimeException('SB-13 database migration supports MySQL/MariaDB only.');
    }

    $databaseName = (string) $pdo->query('SELECT DATABASE()')->fetchColumn();
    if ($databaseName === '') {
        throw new RuntimeException('No MySQL database is selected.');
    }

    $userInfo = db_table_name('user_info');
    $userConf = db_table_name('user_conf');
    $content = db_table_name('content');
    $contentStock = db_table_name('content_stock');
    $qUserInfo = db_table_identifier('user_info');
    $qUserConf = db_table_identifier('user_conf');
    $qContent = db_table_identifier('content');
    $qContentStock = db_table_identifier('content_stock');
    $tableNamesSql = "'" . implode("','", sb13_tables()) . "'";

    $snapshot = [
        'schema_version' => SB13_SCHEMA_VERSION,
        'database' => $databaseName,
        'table_prefix' => (string) DB_TABLE_PREFIX,
        'captured_at' => app_now(),
        'present_tables' => [],
        'row_counts' => [],
        'active_counts' => [],
        'content_location_counts' => [],
        'content_owner_counts' => [],
        'stock_owner_counts' => [],
        'duplicate_identity_groups' => 0,
        'duplicate_user_conf_user_ids' => 0,
        'orphan_content_rows' => 0,
        'orphan_stock_rows' => 0,
        'orphan_conf_rows' => 0,
        'users_missing_conf' => 0,
        'negative_relationship_ids' => 0,
        'table_collations' => [],
        'columns' => [],
        'indexes' => [],
    ];

    $tableStmt = $pdo->prepare(
        'SELECT TABLE_NAME, TABLE_COLLATION FROM information_schema.TABLES '
        . 'WHERE TABLE_SCHEMA = :schema AND TABLE_NAME IN (' . $tableNamesSql . ') ORDER BY TABLE_NAME'
    );
    $tableStmt->execute([':schema' => $databaseName]);
    foreach ($tableStmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
        $table = (string) $row['TABLE_NAME'];
        $snapshot['present_tables'][] = $table;
        $snapshot['table_collations'][$table] = (string) ($row['TABLE_COLLATION'] ?? '');
    }

    // Stop before querying missing tables; classification will explain the gate.
    foreach (sb13_tables() as $table) {
        if (!in_array($table, $snapshot['present_tables'], true)) {
            continue;
        }
        // $table is generated by db_table_name() from a strict identifier allowlist.
        $snapshot['row_counts'][$table] = (int) $pdo->query("SELECT COUNT(*) FROM `{$table}`")->fetchColumn();
    }

    if (in_array($userInfo, $snapshot['present_tables'], true)) {
        $snapshot['active_counts']['users'] = (int) $pdo->query("SELECT COUNT(*) FROM {$qUserInfo} WHERE user_flag = 0")->fetchColumn();
        $snapshot['duplicate_identity_groups'] = (int) $pdo->query(
            "SELECT COUNT(*) FROM (SELECT user_email FROM {$qUserInfo} GROUP BY user_email HAVING COUNT(*) > 1) AS d"
        )->fetchColumn();
    }

    if (in_array($content, $snapshot['present_tables'], true)) {
        $snapshot['active_counts']['content'] = (int) $pdo->query("SELECT COUNT(*) FROM {$qContent} WHERE content_flag = 0")->fetchColumn();
        $snapshot['content_location_counts'] = [];
        foreach ($pdo->query("SELECT content_location, COUNT(*) AS c FROM {$qContent} GROUP BY content_location ORDER BY content_location")->fetchAll(PDO::FETCH_ASSOC) as $row) {
            $snapshot['content_location_counts'][(string) $row['content_location']] = (int) $row['c'];
        }
        foreach ($pdo->query("SELECT content_owner, COUNT(*) AS c FROM {$qContent} GROUP BY content_owner ORDER BY content_owner")->fetchAll(PDO::FETCH_ASSOC) as $row) {
            $snapshot['content_owner_counts'][(string) $row['content_owner']] = (int) $row['c'];
        }
    }

    if (in_array($contentStock, $snapshot['present_tables'], true)) {
        $snapshot['active_counts']['stock'] = (int) $pdo->query("SELECT COUNT(*) FROM {$qContentStock} WHERE stock_flag = 0")->fetchColumn();
        foreach ($pdo->query("SELECT stock_owner, COUNT(*) AS c FROM {$qContentStock} GROUP BY stock_owner ORDER BY stock_owner")->fetchAll(PDO::FETCH_ASSOC) as $row) {
            $snapshot['stock_owner_counts'][(string) $row['stock_owner']] = (int) $row['c'];
        }
    }

    if (count(array_intersect([$userInfo, $content], $snapshot['present_tables'])) === 2) {
        $snapshot['orphan_content_rows'] = (int) $pdo->query(
            "SELECT COUNT(*) FROM {$qContent} c LEFT JOIN {$qUserInfo} u ON u.user_id = c.content_owner WHERE u.user_id IS NULL"
        )->fetchColumn();
    }
    if (count(array_intersect([$userInfo, $contentStock], $snapshot['present_tables'])) === 2) {
        $snapshot['orphan_stock_rows'] = (int) $pdo->query(
            "SELECT COUNT(*) FROM {$qContentStock} s LEFT JOIN {$qUserInfo} u ON u.user_id = s.stock_owner WHERE u.user_id IS NULL"
        )->fetchColumn();
    }
    if (count(array_intersect([$userInfo, $userConf], $snapshot['present_tables'])) === 2) {
        $snapshot['orphan_conf_rows'] = (int) $pdo->query(
            "SELECT COUNT(*) FROM {$qUserConf} c LEFT JOIN {$qUserInfo} u ON u.user_id = c.user_id WHERE u.user_id IS NULL"
        )->fetchColumn();
        $snapshot['users_missing_conf'] = (int) $pdo->query(
            "SELECT COUNT(*) FROM {$qUserInfo} u LEFT JOIN {$qUserConf} c ON c.user_id = u.user_id WHERE c.user_id IS NULL"
        )->fetchColumn();
        $snapshot['duplicate_user_conf_user_ids'] = (int) $pdo->query(
            "SELECT COUNT(*) FROM (SELECT user_id FROM {$qUserConf} GROUP BY user_id HAVING COUNT(*) > 1) AS d"
        )->fetchColumn();
    }

    $negative = 0;
    if (in_array($userConf, $snapshot['present_tables'], true)) {
        $negative += (int) $pdo->query("SELECT COUNT(*) FROM {$qUserConf} WHERE user_id < 0")->fetchColumn();
    }
    if (in_array($content, $snapshot['present_tables'], true)) {
        $negative += (int) $pdo->query("SELECT COUNT(*) FROM {$qContent} WHERE content_owner < 0")->fetchColumn();
    }
    if (in_array($contentStock, $snapshot['present_tables'], true)) {
        $negative += (int) $pdo->query("SELECT COUNT(*) FROM {$qContentStock} WHERE stock_owner < 0")->fetchColumn();
    }
    $snapshot['negative_relationship_ids'] = $negative;

    $columnStmt = $pdo->prepare(
        'SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA '
        . 'FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = :schema '
        . 'AND TABLE_NAME IN (' . $tableNamesSql . ') ORDER BY TABLE_NAME, ORDINAL_POSITION'
    );
    $columnStmt->execute([':schema' => $databaseName]);
    foreach ($columnStmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
        $snapshot['columns'][(string) $row['TABLE_NAME']][(string) $row['COLUMN_NAME']] = [
            'type' => (string) $row['COLUMN_TYPE'],
            'nullable' => (string) $row['IS_NULLABLE'],
            'default' => $row['COLUMN_DEFAULT'],
            'extra' => (string) $row['EXTRA'],
        ];
    }

    $indexStmt = $pdo->prepare(
        'SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME, SUB_PART '
        . 'FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = :schema '
        . 'AND TABLE_NAME IN (' . $tableNamesSql . ') ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX'
    );
    $indexStmt->execute([':schema' => $databaseName]);
    foreach ($indexStmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
        $table = (string) $row['TABLE_NAME'];
        $index = (string) $row['INDEX_NAME'];
        if (!isset($snapshot['indexes'][$table][$index])) {
            $snapshot['indexes'][$table][$index] = [
                'unique' => (int) $row['NON_UNIQUE'] === 0,
                'columns' => [],
            ];
        }
        $column = (string) $row['COLUMN_NAME'];
        if ($row['SUB_PART'] !== null) {
            $column .= '(' . (int) $row['SUB_PART'] . ')';
        }
        $snapshot['indexes'][$table][$index]['columns'][] = $column;
    }

    return $snapshot;
}

/** @return list<string> */
function sb13_migration_statements(): array
{
    $userInfo = db_table_identifier('user_info');
    $userConf = db_table_identifier('user_conf');
    $content = db_table_identifier('content');
    $contentStock = db_table_identifier('content_stock');

    return [
        "ALTER TABLE {$userInfo} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
        "ALTER TABLE {$userConf} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
        "ALTER TABLE {$content} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
        "ALTER TABLE {$contentStock} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
        "ALTER TABLE {$userConf} MODIFY `user_id` INT UNSIGNED NOT NULL COMMENT 'user_infoのuser_id'",
        "ALTER TABLE {$content} MODIFY `content_owner` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所有者ID[user_info:id]'",
        "ALTER TABLE {$contentStock} MODIFY `stock_owner` INT UNSIGNED NOT NULL COMMENT 'データオーナー'",
        "ALTER TABLE {$userInfo} ADD INDEX `idx_user_identity_flag_id` (`user_email`(64), `user_flag`, `user_id`)",
        "ALTER TABLE {$userConf} ADD UNIQUE INDEX `uq_user_conf_user_id` (`user_id`)",
        "ALTER TABLE {$content} ADD INDEX `idx_content_owner_location_flag_id` (`content_owner`, `content_location`, `content_flag`, `content_id`)",
        "ALTER TABLE {$contentStock} ADD INDEX `idx_stock_owner_flag_id` (`stock_owner`, `stock_flag`, `stock_id`)",
    ];
}

/**
 * Verify schema shape after migration without requiring pre-migration counts.
 *
 * @param array<string, mixed> $snapshot
 * @return list<string>
 */
function sb13_schema_issues(array $snapshot): array
{
    $issues = [];

    foreach (sb13_tables() as $table) {
        $collation = strtolower((string) ($snapshot['table_collations'][$table] ?? ''));
        if ($collation !== SB13_TARGET_COLLATION) {
            $issues[] = "{$table} does not use the target collation " . SB13_TARGET_COLLATION . " (collation={$collation}).";
        }
    }

    foreach (sb13_unsigned_relationship_columns() as $table => $columns) {
        foreach ($columns as $column) {
            $type = strtolower((string) ($snapshot['columns'][$table][$column]['type'] ?? ''));
            if ($type === '' || !str_contains($type, 'unsigned')) {
                $issues[] = "{$table}.{$column} is not UNSIGNED.";
            }
        }
    }

    foreach (sb13_required_indexes() as $table => $required) {
        $actual = $snapshot['indexes'][$table] ?? [];
        foreach ($required as $name => $definition) {
            $found = false;
            foreach ($actual as $actualName => $actualDefinition) {
                if ($name === 'PRIMARY' && $actualName !== 'PRIMARY') {
                    continue;
                }
                if ($name !== 'PRIMARY' && $actualName !== $name) {
                    continue;
                }
                if ((bool) ($actualDefinition['unique'] ?? false) !== $definition['unique']) {
                    continue;
                }
                if (($actualDefinition['columns'] ?? []) !== $definition['columns']) {
                    continue;
                }
                $found = true;
                break;
            }
            if (!$found) {
                $issues[] = "Required index missing or mismatched: {$table}.{$name}";
            }
        }
    }

    return $issues;
}

/**
 * DDL-only migration must preserve not only total rows but also logical-active,
 * location, owner and gate counts.
 *
 * @param array<string, mixed> $before
 * @param array<string, mixed> $after
 * @return list<string>
 */
function sb13_data_consistency_issues(array $before, array $after): array
{
    $issues = sb13_row_count_issues($before, $after);
    $keys = [
        'active_counts',
        'content_location_counts',
        'content_owner_counts',
        'stock_owner_counts',
    ];
    foreach ($keys as $key) {
        if (($before[$key] ?? null) !== ($after[$key] ?? null)) {
            $issues[] = "Data distribution changed during schema migration: {$key}";
        }
    }

    foreach ([
        'duplicate_identity_groups',
        'duplicate_user_conf_user_ids',
        'orphan_content_rows',
        'orphan_stock_rows',
        'orphan_conf_rows',
        'users_missing_conf',
    ] as $key) {
        if (($before[$key] ?? null) !== ($after[$key] ?? null)) {
            $issues[] = "Integrity gate count changed during schema migration: {$key}";
        }
    }

    return $issues;
}

/**
 * Row counts must not change during the DDL-only SB-13 migration.
 *
 * @param array<string, mixed> $before
 * @param array<string, mixed> $after
 * @return list<string>
 */
function sb13_row_count_issues(array $before, array $after): array
{
    $issues = [];
    foreach (sb13_tables() as $table) {
        $a = $before['row_counts'][$table] ?? null;
        $b = $after['row_counts'][$table] ?? null;
        if (!is_int($a) || !is_int($b) || $a !== $b) {
            $issues[] = "Row count changed or unavailable for {$table}: before=" . var_export($a, true) . ', after=' . var_export($b, true);
        }
    }
    return $issues;
}
